import { router } from '../trpc';

import {
  tailMulti,
  diffOutput,
  searchFiles,
  getRuntimeState,
  getHarnessLog,
  getSetupStatus,
  sendPrompt,
  steerTask,
  steerQueuedMessage,
  reorderQueuedMessage,
  deleteQueuedPrompt,
  answerUserInputRequest,
  switchModel,
  sandboxStream,
  cancelTask,
  touchKeepalive,
  reloadDeploymentEnvVars,
  scrubSnapshotSecrets,
  restoreScrubbedCredentials,
} from '../procedures';

export const commandsRouter = router({
  tailMulti,
  diffOutput,
  searchFiles,
  getRuntimeState,
  getHarnessLog,
  getSetupStatus,
  sendPrompt,
  steerTask,
  steerQueuedMessage,
  reorderQueuedMessage,
  deleteQueuedPrompt,
  answerUserInputRequest,
  switchModel,
  sandboxStream,
  cancelTask,
  touchKeepalive,
  reloadDeploymentEnvVars,
  scrubSnapshotSecrets,
  restoreScrubbedCredentials,
});
