import { describe, expect, it } from 'vitest';

import type { AgentMailMessage } from '../agentmail-event';
import {
  getAgentMailDeliveryFailureRecipients,
  getAgentMailMessageBodyText,
  getAgentMailSenderAddress,
  isAgentMailAutoGeneratedMessage,
  isAgentMailMessageBouncedEvent,
  isAgentMailMessageComplainedEvent,
  isAgentMailMessageReceivedEvent,
  isAgentMailPermanentBounce,
  parseAgentMailWebhookEvent,
} from '../agentmail-event';

function buildMessage(
  overrides: Record<string, unknown> = {},
): AgentMailMessage {
  return {
    message_id: 'msg_1',
    thread_id: 'thread_1',
    inbox_id: 'inbox_1',
    from: 'sender@example.test',
    timestamp: '2026-08-31T12:00:00Z',
    ...overrides,
  } as AgentMailMessage;
}

describe('parseAgentMailWebhookEvent', () => {
  it('parses a message.received event and keeps unknown fields', () => {
    const event = parseAgentMailWebhookEvent({
      type: 'event',
      event_type: 'message.received',
      event_id: 'evt_1',
      message: {
        message_id: 'msg_1',
        thread_id: 'thread_1',
        inbox_id: 'inbox_1',
        from: 'Sender <sender@example.test>',
        to: ['agent@inbox.example.test'],
        subject: 'Hello',
        text: 'Hi there',
        timestamp: '2026-08-31T12:00:00Z',
        some_future_field: 'kept',
      },
    });

    expect(event).not.toBeNull();
    expect(event?.event_type).toBe('message.received');
    expect(event && isAgentMailMessageReceivedEvent(event)).toBe(true);
    expect(
      (event?.message as Record<string, unknown> | undefined)
        ?.some_future_field,
    ).toBe('kept');
  });

  it('returns null for payloads missing required fields', () => {
    expect(parseAgentMailWebhookEvent({ message: {} })).toBeNull();
    expect(parseAgentMailWebhookEvent('not an object')).toBeNull();
  });

  it('accepts array and object address forms', () => {
    const event = parseAgentMailWebhookEvent({
      event_type: 'message.received',
      message: {
        message_id: 'msg_1',
        thread_id: 'thread_1',
        inbox_id: 'inbox_1',
        from: [{ address: 'sender@example.test', name: 'Sender' }],
        timestamp: '2026-08-31T12:00:00Z',
      },
    });

    expect(event?.message).toBeDefined();
  });
});

describe('getAgentMailSenderAddress', () => {
  it('normalizes the angle-bracket display form to a lowercased address', () => {
    expect(
      getAgentMailSenderAddress(buildMessage({ from: 'Name <a@B.example>' })),
    ).toBe('a@b.example');
  });

  it('accepts bare addresses and arrays', () => {
    expect(
      getAgentMailSenderAddress(buildMessage({ from: 'A@Example.Test' })),
    ).toBe('a@example.test');
    expect(
      getAgentMailSenderAddress(
        buildMessage({ from: ['First <first@example.test>', 'x@y.test'] }),
      ),
    ).toBe('first@example.test');
  });

  it('reads address objects and returns null when no address exists', () => {
    expect(
      getAgentMailSenderAddress(
        buildMessage({ from: { email: 'Obj@Example.Test', name: 'Obj' } }),
      ),
    ).toBe('obj@example.test');
    expect(getAgentMailSenderAddress(buildMessage({ from: [] }))).toBeNull();
    expect(
      getAgentMailSenderAddress(buildMessage({ from: 'not-an-address' })),
    ).toBeNull();
  });
});

describe('getAgentMailMessageBodyText', () => {
  it('ignores close tags embedded in the opening tag attributes', () => {
    expect(
      getAgentMailMessageBodyText(
        buildMessage({
          html: '<script data-note="</script>">hidden()</script>visible',
        }),
      ),
    ).toBe('visible');
  });

  it('ignores a ">" inside a quoted attribute before an embedded close tag', () => {
    expect(
      getAgentMailMessageBodyText(
        buildMessage({
          html: '<script data-note="> </script>">hidden()</script>visible',
        }),
      ),
    ).toBe('visible');
    expect(
      getAgentMailMessageBodyText(
        buildMessage({
          html: '<style media=\'>\' data-x="</style>">.a{}</style>after',
        }),
      ),
    ).toBe('after');
  });

  it('does not treat tags that merely start with script/style as blocks', () => {
    expect(
      getAgentMailMessageBodyText(
        buildMessage({
          html: '<scripture>keep me</scripture> and <script>drop()</script>done',
        }),
      ),
    ).toBe('keep me and done');
  });

  it('keeps neighboring text separated when script/style blocks are removed', () => {
    expect(
      getAgentMailMessageBodyText(
        buildMessage({
          html: 'Please<script>tracking()</script>review<style>.x{}</style>this',
        }),
      ),
    ).toBe('Please review this');
  });

  it('prefers extracted_text over text and html', () => {
    expect(
      getAgentMailMessageBodyText(
        buildMessage({
          extracted_text: '  extracted  ',
          text: 'raw text',
          html: '<p>html</p>',
        }),
      ),
    ).toBe('extracted');
  });

  it('falls back to text before html', () => {
    expect(
      getAgentMailMessageBodyText(
        buildMessage({ text: 'raw text', html: '<p>html</p>' }),
      ),
    ).toBe('raw text');
  });

  it('strips tags from the html fallback', () => {
    expect(
      getAgentMailMessageBodyText(
        buildMessage({ html: '<div><p>Hello <b>world</b></p></div>' }),
      ),
    ).toBe('Hello world');
    expect(getAgentMailMessageBodyText(buildMessage({}))).toBe('');
  });
});

describe('isAgentMailAutoGeneratedMessage', () => {
  it('detects Auto-Submitted headers case-insensitively', () => {
    expect(
      isAgentMailAutoGeneratedMessage(
        buildMessage({ headers: { 'auto-submitted': 'auto-replied' } }),
      ),
    ).toBe(true);
    expect(
      isAgentMailAutoGeneratedMessage(
        buildMessage({ headers: { 'Auto-Submitted': 'no' } }),
      ),
    ).toBe(false);
  });

  it('detects bulk/list/junk precedence', () => {
    expect(
      isAgentMailAutoGeneratedMessage(
        buildMessage({ headers: { Precedence: 'Bulk' } }),
      ),
    ).toBe(true);
    expect(
      isAgentMailAutoGeneratedMessage(
        buildMessage({ headers: { Precedence: 'first-class' } }),
      ),
    ).toBe(false);
  });

  it('tolerates missing or malformed headers', () => {
    expect(isAgentMailAutoGeneratedMessage(buildMessage({}))).toBe(false);
    expect(
      isAgentMailAutoGeneratedMessage(buildMessage({ headers: 'nope' })),
    ).toBe(false);
    expect(
      isAgentMailAutoGeneratedMessage(
        buildMessage({ labels: ['Auto-Generated'] }),
      ),
    ).toBe(true);
  });
});

describe('delivery-failure events', () => {
  it('parses a message.bounced payload with object recipients', () => {
    const event = parseAgentMailWebhookEvent({
      type: 'event',
      event_type: 'message.bounced',
      event_id: 'evt_1',
      bounce: {
        inbox_id: 'inbox_1',
        thread_id: 'thread_1',
        message_id: '<abc@agentmail.to>',
        timestamp: '2026-08-31T12:00:00Z',
        type: 'Permanent',
        sub_type: 'General',
        recipients: [
          { address: 'Invalid@Example.test', status: 'bounced' },
          { address: 'invalid@example.test', status: 'bounced' },
        ],
      },
    });

    expect(event).not.toBeNull();
    expect(isAgentMailMessageBouncedEvent(event!)).toBe(true);
    expect(isAgentMailMessageComplainedEvent(event!)).toBe(false);
    expect(isAgentMailPermanentBounce(event!.bounce!)).toBe(true);
    expect(getAgentMailDeliveryFailureRecipients(event!.bounce!)).toEqual([
      'invalid@example.test',
    ]);
  });

  it('parses a message.complained payload with string recipients', () => {
    const event = parseAgentMailWebhookEvent({
      type: 'event',
      event_type: 'message.complained',
      event_id: 'evt_2',
      complaint: {
        inbox_id: 'inbox_1',
        message_id: '<def@agentmail.to>',
        type: 'abuse',
        sub_type: 'spam',
        recipients: ['Complainer@Example.test'],
      },
    });

    expect(event).not.toBeNull();
    expect(isAgentMailMessageComplainedEvent(event!)).toBe(true);
    expect(getAgentMailDeliveryFailureRecipients(event!.complaint!)).toEqual([
      'complainer@example.test',
    ]);
  });

  it('treats only Permanent bounces as permanent', () => {
    expect(isAgentMailPermanentBounce({ inbox_id: 'i' })).toBe(false);
    expect(
      isAgentMailPermanentBounce({ inbox_id: 'i', type: 'Transient' }),
    ).toBe(false);
    expect(
      isAgentMailPermanentBounce({ inbox_id: 'i', type: 'permanent' }),
    ).toBe(true);
  });

  it('drops recipients without a parseable address', () => {
    expect(
      getAgentMailDeliveryFailureRecipients({
        inbox_id: 'i',
        recipients: ['not-an-address', { status: 'bounced' }],
      }),
    ).toEqual([]);
  });
});
