import type { UserAuthSuccess } from '@/types';

import {
  findAccessibleFastSession,
  getFastSessionSuggestableMessages,
} from '@/lib/server/fast-sessions';
import {
  type ComposerSuggestionResult,
  suggestNextComposerMessage,
} from '@/lib/server/composer-suggestion';

/**
 * Suggest the user's likely next composer message for a fast session,
 * generated by the deployment helper model from the persisted conversation.
 * Fails soft: any error returns a null suggestion so the composer is never
 * blocked.
 */
export async function getFastSessionComposerSuggestionCommand(
  auth: UserAuthSuccess,
  input: { sessionId: string },
): Promise<ComposerSuggestionResult> {
  try {
    const session = await findAccessibleFastSession(auth, input.sessionId);

    if (!session) {
      return { suggestion: null, messageCount: 0 };
    }

    const messages = await getFastSessionSuggestableMessages(session.id);

    return await suggestNextComposerMessage({
      messages,
      cacheScope: `session:${session.id}`,
      userId: auth.userId ?? null,
      fastConversationId: session.id,
    });
  } catch (error) {
    console.error(
      'Error loading session history for composer suggestion:',
      error,
    );
    return { suggestion: null, messageCount: 0 };
  }
}
