import type { UserAuthSuccess } from '@/types';

import {
  findAccessibleFastSession,
  getFastSessionSuggestableMessages,
  getFastSessionTasks,
} from '@/lib/server/fast-sessions';
import {
  type ComposerSuggestionResult,
  suggestNextComposerMessage,
} from '@/lib/server/composer-suggestion';
import { computeTaskStateRevision } from '@/lib/composer-suggestion-task-state';

// Bound the task context so a session with many delegations stays cheap.
const MAX_CONTEXT_TASKS = 20;

/**
 * The session's delegated tasks as a compact context block. Their live state
 * (running, waiting, failed) is exactly what the transcript text cannot
 * convey, so the suggestion can reference it. Fails soft to no context.
 */
async function buildSessionTaskContext(
  auth: UserAuthSuccess,
  sessionId: string,
): Promise<{ context: string | null; revision: string | null }> {
  try {
    const tasks = await getFastSessionTasks(auth, sessionId);

    if (!tasks || tasks.length === 0) {
      return { context: null, revision: null };
    }

    const lines = tasks.slice(0, MAX_CONTEXT_TASKS).map((task) => {
      const title = task.title?.trim() || 'Untitled task';
      const state = [task.latestRun.status, task.latestRun.taskPhase]
        .filter(Boolean)
        .join(', ');
      const artifacts =
        task.artifacts.length > 0
          ? `, ${task.artifacts.length} artifact${task.artifacts.length === 1 ? '' : 's'}`
          : '';
      return `- ${title} (${state}${artifacts})`;
    });

    return {
      context: [
        'Tasks the agent has delegated in this session, with their current status:',
        ...lines,
      ].join('\n'),
      revision: computeTaskStateRevision(tasks),
    };
  } catch (error) {
    console.error(
      'Error loading session tasks for composer suggestion:',
      error,
    );
    return { context: null, revision: null };
  }
}

/**
 * Suggest the user's likely next composer message for a fast session,
 * generated by the deployment helper model from the persisted conversation.
 * Fails soft: any error returns a null suggestion so the composer is never
 * blocked.
 */
export async function getFastSessionComposerSuggestionCommand(
  auth: UserAuthSuccess,
  input: { sessionId: string },
): Promise<ComposerSuggestionResult> {
  if (auth.featureFlags?.composerSuggestions !== true) {
    return { suggestion: null, messageCount: 0 };
  }

  try {
    const session = await findAccessibleFastSession(auth, input.sessionId);

    if (!session) {
      return { suggestion: null, messageCount: 0 };
    }

    const [messages, taskContext] = await Promise.all([
      getFastSessionSuggestableMessages(session.id),
      buildSessionTaskContext(auth, session.id),
    ]);

    return await suggestNextComposerMessage({
      messages,
      cacheScope: `session:${session.id}`,
      userId: auth.userId ?? null,
      fastConversationId: session.id,
      context: taskContext.context,
      contextRevision: taskContext.revision,
    });
  } catch (error) {
    console.error(
      'Error loading session history for composer suggestion:',
      error,
    );
    return { suggestion: null, messageCount: 0 };
  }
}
