import type { FeatureFlagConfigMap, MetadataBooleanDescriptor } from './types';

export const FEATURE_FLAG_CONFIG: FeatureFlagConfigMap = {
  composerSuggestions: {
    defaultValue: false,
    group: 'experimental',
    description:
      'Show a suggested follow-up message in the task and session composers after each completed agent turn. Generated by the deployment helper model (one small inference call per turn per conversation).',
  },
};

/**
 * Non-feature-flag boolean deployment metadata that is still actively read in
 * the product and should be treated as first-class admin controls.
 */
export const DEPLOYMENT_METADATA_BOOLEAN_CONFIG: Record<
  string,
  MetadataBooleanDescriptor
> = {
  deployment_disabled: {
    kind: 'deployment-control',
    group: null,
    description:
      'Disable Roomote access and new task launches for this deployment',
  },
  anonymous_analytics_enabled: {
    kind: 'deployment-control',
    group: null,
    description:
      'Share anonymous usage analytics (instance and user activity identified only by random IDs) with the Roomote team. Enabled by default; absent means enabled.',
  },
};
