#!/usr/bin/env bash
# Reads roomote-ios.json and writes the per-deployment build inputs:
#   Config/Deployment.xcconfig            build settings (bundle id, team, name, URL)
#   Config/Generated/*.entitlements       keychain group, app group, APNs, associated domains
#
# Usage: scripts/configure.sh [path/to/roomote-ios.json]
# The config path can also be given through ROOMOTE_IOS_CONFIG.
set -euo pipefail

cd "$(dirname "$0")/.."
CONFIG="${1:-${ROOMOTE_IOS_CONFIG:-roomote-ios.json}}"

if [[ ! -f "$CONFIG" ]]; then
  if [[ -f roomote-ios.example.json ]]; then
    echo "configure: $CONFIG not found, falling back to roomote-ios.example.json" >&2
    CONFIG=roomote-ios.example.json
  else
    echo "configure: $CONFIG not found" >&2
    exit 1
  fi
fi

# read_key <key> [default]        -> scalar value
# read_list <key>                 -> one element per line
if command -v jq >/dev/null 2>&1; then
  read_key() { jq -r --arg k "$1" --arg d "${2:-}" '.[$k] // $d | tostring' "$CONFIG"; }
  read_list() { jq -r --arg k "$1" '(.[$k] // [])[]' "$CONFIG"; }
else
  read_key() { python3 - "$CONFIG" "$1" "${2:-}" <<'PY'
import json, sys
data = json.load(open(sys.argv[1]))
value = data.get(sys.argv[2])
print(sys.argv[3] if value is None else value)
PY
  }
  read_list() { python3 - "$CONFIG" "$1" <<'PY'
import json, sys
data = json.load(open(sys.argv[1]))
for item in data.get(sys.argv[2]) or []:
    print(item)
PY
  }
fi

BUNDLE_ID="$(read_key bundleId dev.roomote.app)"
TEAM_ID="$(read_key teamId "")"
DISPLAY_NAME="$(read_key displayName Roomote)"
DEPLOYMENT_URL="$(read_key deploymentUrl http://localhost:3000)"
DEPLOYMENT_URL="${DEPLOYMENT_URL%/}"
ASSOCIATED_DOMAINS=()
while IFS= read -r domain; do
  [[ -n "$domain" ]] && ASSOCIATED_DOMAINS+=("$domain")
done < <(read_list associatedDomains)

if [[ ! "$BUNDLE_ID" =~ ^[A-Za-z0-9.-]+$ ]]; then
  echo "configure: invalid bundleId '$BUNDLE_ID'" >&2
  exit 1
fi
if [[ ! "$DEPLOYMENT_URL" =~ ^https?:// ]]; then
  echo "configure: deploymentUrl must start with http:// or https://" >&2
  exit 1
fi

# xcconfig treats `//` as a comment. The documented workaround is an empty
# variable reference in the middle: `https:/$()/host`.
XCCONFIG_URL="${DEPLOYMENT_URL//\/\//\/\$()\/}"

mkdir -p Config Config/Generated

cat > Config/Deployment.xcconfig <<XC
// Generated by scripts/configure.sh from $CONFIG. Do not edit; edit the JSON instead.
ROOMOTE_BUNDLE_ID = $BUNDLE_ID
PRODUCT_BUNDLE_IDENTIFIER = \$(ROOMOTE_BUNDLE_ID)
DEVELOPMENT_TEAM = $TEAM_ID
ROOMOTE_DISPLAY_NAME = $DISPLAY_NAME
ROOMOTE_DEPLOYMENT_URL = $XCCONFIG_URL
ROOMOTE_KEYCHAIN_ACCESS_GROUP = \$(AppIdentifierPrefix)\$(ROOMOTE_BUNDLE_ID).shared
ROOMOTE_APP_GROUP = group.\$(ROOMOTE_BUNDLE_ID)
ROOMOTE_APS_ENVIRONMENT = development
ROOMOTE_APS_ENVIRONMENT[config=Release] = production
XC

associated_domains_xml() {
  if [[ ${#ASSOCIATED_DOMAINS[@]} -eq 0 ]]; then
    return
  fi
  echo "	<key>com.apple.developer.associated-domains</key>"
  echo "	<array>"
  for domain in "${ASSOCIATED_DOMAINS[@]}"; do
    case "$domain" in
      applinks:*|webcredentials:*|activitycontinuation:*) entry="$domain" ;;
      *) entry="applinks:$domain" ;;
    esac
    echo "		<string>$entry</string>"
  done
  echo "	</array>"
}

shared_entitlements_xml() {
  cat <<XML
	<key>keychain-access-groups</key>
	<array>
		<string>\$(AppIdentifierPrefix)\$(ROOMOTE_BUNDLE_ID).shared</string>
	</array>
	<key>com.apple.security.application-groups</key>
	<array>
		<string>group.\$(ROOMOTE_BUNDLE_ID)</string>
	</array>
XML
}

write_entitlements() {
  local path="$1" include_push="$2" include_domains="$3"
  {
    echo '<?xml version="1.0" encoding="UTF-8"?>'
    echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">'
    echo '<plist version="1.0">'
    echo '<dict>'
    shared_entitlements_xml
    if [[ "$include_push" == "1" ]]; then
      echo "	<key>aps-environment</key>"
      echo "	<string>\$(ROOMOTE_APS_ENVIRONMENT)</string>"
    fi
    if [[ "$include_domains" == "1" ]]; then
      associated_domains_xml
    fi
    echo '</dict>'
    echo '</plist>'
  } > "$path"
}

write_entitlements Config/Generated/Roomote.entitlements 1 1
write_entitlements Config/Generated/RoomoteShare.entitlements 0 0
write_entitlements Config/Generated/RoomoteNotificationService.entitlements 0 0

echo "configure: bundleId=$BUNDLE_ID team=${TEAM_ID:-<none>} name='$DISPLAY_NAME' url=$DEPLOYMENT_URL domains=${#ASSOCIATED_DOMAINS[@]}"
