import { Queue } from 'bullmq';

import {
  AgentMailApiClient,
  AgentMailApiError,
  escapeAgentMailHtml,
  getAgentMailDeliveryFailureRecipients,
  getAgentMailMessageBodyText,
  getAgentMailSenderAddress,
  getPendingCommunicationRequestUserInput,
  isAgentMailAutoGeneratedMessage,
  isAgentMailMessageBouncedEvent,
  isAgentMailMessageComplainedEvent,
  isAgentMailMessageReceivedEvent,
  isAgentMailPermanentBounce,
  normalizeAgentMailAddress,
  parseAgentMailWebhookEvent,
  queueCommunicationMessageOnce,
  setLatestInboundMessageId,
  submitPendingCommunicationRequestUserInputAnswer,
  type AgentMailMessage,
} from '@roomote/communication';
import {
  acquireFastAgentTurnLock,
  getOrCreateFastAgentSession,
  type FastAgentTurnLockHandle,
} from '@roomote/cloud-agents/server';
import {
  agentmailConversations,
  agentmailInboundTurns,
  agentmailWebhookEvents,
  and,
  asc,
  db,
  eq,
  isNull,
  lt,
  lte,
  or,
  resolveAgentMailRuntimeCredentials,
  setTrustedRunActingUserOnSuccess,
  sql,
} from '@roomote/db/server';
import { isEmailChannelEnabled } from '@roomote/env';
import { getRedis } from '@roomote/redis';
import {
  parseAcpRequestUserInputAnswerReply,
  type FastAgentConversation,
} from '@roomote/types';

import {
  isAgentMailAddressSuppressed,
  suppressAgentMailAddress,
} from './outbound';
import {
  advanceAgentMailInboundAnchor,
  normalizeEmailAddress,
  resolveAgentMailSenderUserId,
  resolveOrCreateAgentMailConversation,
  type AgentMailConversationRow,
} from './conversation-store';
import { findActiveCommunicationTaskRun } from '../communication/communication-task-run-lookup';
import { continueFastAgentSurfaceReplyWithLock } from '../fast-agent-surface-reply';

export const AGENTMAIL_WEBHOOK_EVENT_QUEUE_NAME = 'agentmail-webhook-events';

const LOG_PREFIX = '[agentmail]';
const STRANGER_REFUSAL_TTL_SECONDS = 30 * 24 * 60 * 60;
// Beyond the per-thread claim: one refusal per unknown sender per day (its
// guidance covers every thread they wrote to), and a global daily ceiling so
// a spam wave of fresh threads cannot burn the deployment's send quota.
const STRANGER_REFUSAL_SENDER_TTL_SECONDS = 24 * 60 * 60;
const STRANGER_REFUSAL_DAILY_CAP = 25;
const FAILED_EVENT_ATTEMPT_CAP = 10;
const FAILED_TURN_ATTEMPT_CAP = 5;
const RECOVERY_SWEEP_BATCH_SIZE = 500;
const RECOVERY_STALE_AFTER_MS = 60_000;
// A parked turn resumes through the parent-event queue at its retry time;
// the drain wakes slightly after so the queue's resumption usually wins the
// lock and the drain only has to notice the settled row.
const PARKED_TURN_DRAIN_GRACE_MS = 2_000;

export type AgentMailWebhookEventJob =
  | { kind: 'process'; deliveryId: string }
  | { kind: 'drain'; conversationId: string };

export class AgentMailConversationBusyError extends Error {
  constructor() {
    super('AgentMail conversation is busy; retry the durable queue later.');
    this.name = 'AgentMailConversationBusyError';
  }
}

let webhookEventQueue: Queue<AgentMailWebhookEventJob> | null = null;

function getWebhookEventQueue() {
  webhookEventQueue ??= new Queue<AgentMailWebhookEventJob>(
    AGENTMAIL_WEBHOOK_EVENT_QUEUE_NAME,
    {
      connection: getRedis(),
      defaultJobOptions: {
        attempts: 5,
        backoff: { type: 'exponential', delay: 2_000 },
        removeOnComplete: true,
        // PostgreSQL is the source of truth (agentmail_webhook_events /
        // agentmail_inbound_turns); the recovery sweep recreates wakeups.
        removeOnFail: true,
      },
    },
  );
  return webhookEventQueue;
}

function sanitizeJobIdPart(value: string): string {
  // BullMQ job ids reject ':'; keep them to a safe charset.
  return value.replace(/[^a-zA-Z0-9_-]/g, '-');
}

async function addProcessJob(deliveryId: string) {
  await getWebhookEventQueue().add(
    'process',
    { kind: 'process', deliveryId },
    { jobId: `process-${sanitizeJobIdPart(deliveryId)}` },
  );
}

async function addDrainJob(
  conversationId: string,
  dedupeSuffix: string,
  options: { delayMs?: number } = {},
) {
  // Each admitted turn gets its own wakeup: a drain job id shared per
  // conversation could be silently dropped while a previous drain is still
  // active, stranding the new turn until the sweeper.
  await getWebhookEventQueue().add(
    'drain',
    { kind: 'drain', conversationId },
    {
      jobId: `drain-${sanitizeJobIdPart(conversationId)}-${sanitizeJobIdPart(dedupeSuffix)}`,
      ...(options.delayMs && options.delayMs > 0
        ? { delay: options.delayMs }
        : {}),
    },
  );
}

/**
 * Wake the drain once a parked turn's retry time has passed. The job id is
 * keyed on the retry time, so repeated sweeps of the same parked turn share
 * one wakeup instead of minting a new delayed job each minute.
 */
async function scheduleDrainAfterRetry(conversationId: string, retryAt: Date) {
  await addDrainJob(conversationId, `retry-${retryAt.getTime()}`, {
    delayMs: Math.max(
      0,
      retryAt.getTime() + PARKED_TURN_DRAIN_GRACE_MS - Date.now(),
    ),
  });
}

type RecordAgentMailWebhookEventResult =
  | { accepted: true; duplicate: boolean }
  | {
      accepted: false;
      reason: 'ignored_event_type' | 'email_channel_disabled';
    };

/**
 * The ingestion outbox: record the verified delivery durably, then dispatch.
 * No transaction spans Postgres and Redis, so the row (state `received`) is
 * the commitment; it moves to `queued` only after BullMQ accepts the job. A
 * duplicate delivery checks row state: a still-`received` row means the
 * earlier attempt crashed between insert and enqueue and is re-dispatched;
 * anything further along is acked untouched. Never a blind 200 on conflict.
 */
const ACCEPTED_EVENT_TYPES = new Set([
  'message.received',
  // Delivery-failure events feed the outbound suppression list; recipients
  // who bounce permanently or complain must never be emailed again.
  'message.bounced',
  'message.complained',
]);

export async function recordAgentMailWebhookEvent(input: {
  deliveryId: string;
  eventId: string | null;
  eventType: string;
  payload: unknown;
}): Promise<RecordAgentMailWebhookEventResult> {
  // The rollout gate is a real kill switch: a webhook that is still
  // registered at AgentMail is acknowledged and dropped, never queued.
  if (!isEmailChannelEnabled()) {
    return { accepted: false, reason: 'email_channel_disabled' };
  }
  if (!ACCEPTED_EVENT_TYPES.has(input.eventType)) {
    return { accepted: false, reason: 'ignored_event_type' };
  }

  const inserted = await db
    .insert(agentmailWebhookEvents)
    .values({
      deliveryId: input.deliveryId,
      eventId: input.eventId,
      eventType: input.eventType,
      payload: input.payload as Record<string, unknown>,
    })
    .onConflictDoNothing({ target: agentmailWebhookEvents.deliveryId })
    .returning({ id: agentmailWebhookEvents.id });

  const duplicate = inserted.length === 0;

  if (duplicate) {
    const existing = await db.query.agentmailWebhookEvents.findFirst({
      where: eq(agentmailWebhookEvents.deliveryId, input.deliveryId),
      columns: { state: true },
    });
    if (existing && existing.state !== 'received') {
      return { accepted: true, duplicate: true };
    }
  }

  try {
    await addProcessJob(input.deliveryId);
    await db
      .update(agentmailWebhookEvents)
      .set({ state: 'queued', updatedAt: new Date() })
      .where(
        and(
          eq(agentmailWebhookEvents.deliveryId, input.deliveryId),
          eq(agentmailWebhookEvents.state, 'received'),
        ),
      );
  } catch (error) {
    // Admission is already durable; the recovery sweep re-dispatches
    // `received` rows without making AgentMail retry carry the burden.
    console.error(
      `${LOG_PREFIX} Recorded delivery ${input.deliveryId}, but its immediate dispatch failed: ${error instanceof Error ? error.message : String(error)}`,
    );
  }

  return { accepted: true, duplicate };
}

function buildAgentMailFastConversation(
  conversation: Pick<AgentMailConversationRow, 'id' | 'inboxId'>,
): Extract<FastAgentConversation, { surface: 'agentmail' }> {
  return {
    surface: 'agentmail',
    workspaceId: conversation.inboxId,
    // The INTERNAL conversation id, never the provider thread id: forwarded
    // threads fork into a second conversation on the same provider thread.
    conversationId: conversation.id,
    replyTarget: {
      channelId: conversation.inboxId,
      threadId: conversation.id,
    },
  };
}

async function markEventProcessed(id: string) {
  await db
    .update(agentmailWebhookEvents)
    .set({ state: 'processed', lastError: null, updatedAt: new Date() })
    .where(eq(agentmailWebhookEvents.id, id));
}

async function markEventFailed(id: string, error: unknown) {
  await db
    .update(agentmailWebhookEvents)
    .set({
      state: 'failed',
      lastError: error instanceof Error ? error.message : String(error),
      updatedAt: new Date(),
    })
    .where(eq(agentmailWebhookEvents.id, id));
}

function parseProviderTimestamp(message: AgentMailMessage): Date {
  const parsed = message.timestamp ? new Date(message.timestamp) : null;
  return parsed && !Number.isNaN(parsed.getTime()) ? parsed : new Date();
}

function collectRecipientAddresses(
  message: AgentMailMessage,
  senderAddress: string,
): string[] {
  const raw = [...(message.to ?? []), ...(message.cc ?? [])];
  const normalized = raw
    .map((value) => normalizeAgentMailAddress(value))
    .filter((value): value is string => Boolean(value))
    .map(normalizeEmailAddress);
  return [...new Set(normalized)].filter(
    (address) => address !== senderAddress,
  );
}

function strangerRefusalDailyKey(now = new Date()): string {
  return `agentmail:stranger_refusal:daily:${now.toISOString().slice(0, 10)}`;
}

/**
 * One refusal per unknown address per provider thread, at most one per
 * unknown address per day, under a global daily ceiling, and never for
 * auto-generated mail or a suppressed address, so a stranger's email cannot
 * start a reply loop, drain the send quota, or reach someone who complained.
 */
async function maybeSendStrangerRefusal(input: {
  client: AgentMailApiClient;
  inboxId: string;
  message: AgentMailMessage;
  senderAddress: string;
}): Promise<void> {
  if (await isAgentMailAddressSuppressed(input.senderAddress)) {
    return;
  }

  const redis = getRedis();
  const key = `agentmail:stranger_refusal:${input.inboxId}:${input.message.thread_id}:${input.senderAddress}`;
  const claimed = await redis.set(
    key,
    '1',
    'EX',
    STRANGER_REFUSAL_TTL_SECONDS,
    'NX',
  );
  if (claimed !== 'OK') {
    return;
  }

  const senderKey = `agentmail:stranger_refusal:sender:${input.senderAddress}`;
  const senderClaimed = await redis.set(
    senderKey,
    '1',
    'EX',
    STRANGER_REFUSAL_SENDER_TTL_SECONDS,
    'NX',
  );
  if (senderClaimed !== 'OK') {
    return;
  }

  const dailyKey = strangerRefusalDailyKey();
  const dailyCount = await redis.incr(dailyKey);
  if (dailyCount === 1) {
    await redis.expire(dailyKey, 2 * STRANGER_REFUSAL_SENDER_TTL_SECONDS);
  }
  if (dailyCount > STRANGER_REFUSAL_DAILY_CAP) {
    // Release both claims so the sender still gets a refusal for this thread
    // tomorrow, once the ceiling resets.
    await redis.del(key, senderKey).catch(() => undefined);
    console.warn(
      `${LOG_PREFIX} Stranger refusal daily cap (${STRANGER_REFUSAL_DAILY_CAP}) reached; not replying to ${input.senderAddress} on thread ${input.message.thread_id}`,
    );
    return;
  }

  try {
    const refusalText = `This address isn't the verified email on a Roomote account, so I can't act on this email. Send it again from your account's verified email address, or verify this address under Settings > Personal > Linked Accounts first.`;
    await input.client.replyToMessage(
      input.inboxId,
      input.message.message_id,
      {
        text: refusalText,
        html: `<div><p>${escapeAgentMailHtml(refusalText)}</p></div>`,
      },
      {
        idempotencyKey: `agentmail:refusal:${input.message.message_id}`,
      },
    );
  } catch (error) {
    // Release the once-per-thread claim only on a definite rejection (4xx:
    // the provider did not process the request), so a later email from this
    // sender still gets its refusal. A 5xx or network failure is ambiguous —
    // AgentMail may have sent the refusal before failing — and a kept claim
    // (worst case: one refusal silently lost) beats a released one (worst
    // case: duplicate refusals on the next email, whose different message-id
    // idempotency key would not dedupe them).
    const definitelyNotSent =
      error instanceof AgentMailApiError &&
      error.status >= 400 &&
      error.status < 500;
    if (definitelyNotSent) {
      await redis.del(key, senderKey).catch(() => undefined);
    }
    console.warn(
      `${LOG_PREFIX} Failed to send stranger refusal for thread ${input.message.thread_id} (claim ${definitelyNotSent ? 'released' : 'kept'}): ${error instanceof Error ? error.message : String(error)}`,
    );
  }
}

/**
 * Suppress the recipients of a permanent bounce or a spam complaint so no
 * future outbound-initiated email targets them. Transient bounces (full
 * mailbox, greylisting) are logged, never suppressed. Idempotent: suppression
 * writes are first-reason-wins upserts.
 */
async function processDeliveryFailureEvent(
  event: NonNullable<ReturnType<typeof parseAgentMailWebhookEvent>>,
): Promise<void> {
  const complained = isAgentMailMessageComplainedEvent(event);
  const failure = complained ? event.complaint : event.bounce;
  if (!failure) {
    return;
  }

  if (!complained && !isAgentMailPermanentBounce(failure)) {
    console.info(
      `${LOG_PREFIX} Transient bounce for message ${failure.message_id ?? 'unknown'} (${failure.sub_type ?? 'no sub_type'}); not suppressing.`,
    );
    return;
  }

  const recipients = getAgentMailDeliveryFailureRecipients(failure);
  for (const recipient of recipients) {
    const suppressed = await suppressAgentMailAddress({
      emailAddress: recipient,
      reason: complained ? 'complaint' : 'bounce',
      details: [failure.type, failure.sub_type].filter(Boolean).join('/'),
      providerMessageId: failure.message_id ?? null,
    });
    if (suppressed) {
      console.warn(
        `${LOG_PREFIX} Suppressed ${recipient} after ${complained ? 'spam complaint' : 'permanent bounce'} on message ${failure.message_id ?? 'unknown'}.`,
      );
    }
  }
}

/**
 * Process one recorded delivery: resolve sender and conversation, and admit
 * the message as a durable inbound turn. Marking
 * the event `processed` happens only after the turn insert commits (or after
 * a terminal no-turn outcome such as a stranger refusal); a crash before that
 * leaves the row for retry, never a lost email. Idempotent on the event row.
 */
export async function processAgentMailWebhookEvent(
  deliveryId: string,
): Promise<void> {
  // Disabled mid-flight: leave already-recorded events untouched (still
  // `queued`), so nothing is refused or replied to while off, and the
  // recovery sweep re-dispatches them if the channel is re-enabled.
  if (!isEmailChannelEnabled()) {
    return;
  }
  const row = await db.query.agentmailWebhookEvents.findFirst({
    where: eq(agentmailWebhookEvents.deliveryId, deliveryId),
  });
  if (!row || row.state === 'processed') {
    return;
  }
  if (row.state === 'failed' && row.attempts >= FAILED_EVENT_ATTEMPT_CAP) {
    // True dead letter: the sweep stops re-dispatching past the cap, and a
    // late duplicate delivery must not resurrect it either.
    return;
  }

  await db
    .update(agentmailWebhookEvents)
    .set({
      state: 'processing',
      attempts: sql`${agentmailWebhookEvents.attempts} + 1`,
      updatedAt: new Date(),
    })
    .where(eq(agentmailWebhookEvents.id, row.id));

  try {
    const event = parseAgentMailWebhookEvent(row.payload);
    if (!event) {
      await markEventProcessed(row.id);
      return;
    }

    if (
      isAgentMailMessageBouncedEvent(event) ||
      isAgentMailMessageComplainedEvent(event)
    ) {
      await processDeliveryFailureEvent(event);
      await markEventProcessed(row.id);
      return;
    }

    if (!isAgentMailMessageReceivedEvent(event) || !event.message) {
      await markEventProcessed(row.id);
      return;
    }

    const credentials = await resolveAgentMailRuntimeCredentials();
    if (!credentials.apiKey) {
      throw new Error('AgentMail credentials are no longer configured.');
    }
    const client = new AgentMailApiClient({ apiKey: credentials.apiKey });

    let message = event.message;
    const inboxId = normalizeEmailAddress(message.inbox_id);

    if (isAgentMailAutoGeneratedMessage(message)) {
      // Auto-responders and bounce handlers never get replies and never
      // reach the agent; dropping them here breaks mail loops.
      await markEventProcessed(row.id);
      return;
    }

    // Payloads over the provider's size cap arrive with body fields dropped;
    // re-fetch the full message before routing.
    if (!message.text && !message.extracted_text && !message.html) {
      const fetched = await client.getMessage(inboxId, message.message_id);
      if (fetched) {
        message = { ...message, ...fetched };
      }
    }

    const senderAddress = getAgentMailSenderAddress(message);
    if (!senderAddress || senderAddress === inboxId) {
      await markEventProcessed(row.id);
      return;
    }

    const senderUserId = await resolveAgentMailSenderUserId(senderAddress);
    if (!senderUserId) {
      await maybeSendStrangerRefusal({
        client,
        inboxId,
        message,
        senderAddress,
      });
      await markEventProcessed(row.id);
      return;
    }

    const { conversation } = await resolveOrCreateAgentMailConversation({
      inboxId,
      providerThreadId: message.thread_id,
      senderUserId,
      subject: message.subject?.trim() || null,
      recipientAddresses: collectRecipientAddresses(message, senderAddress),
    });

    const providerTimestamp = parseProviderTimestamp(message);

    // The reply anchor is NOT advanced here. Replies resolve their route from
    // the conversation row at send time, so the anchor must describe the
    // turn being answered, not the latest email to arrive; the drain advances
    // it right before it delivers each turn, in provider order.

    // Admission: inserting this row IS the durable handoff. The webhook
    // event may be marked processed only after this commits. The turn row
    // captures everything the drain needs (including the re-fetched body of
    // oversize deliveries), so consuming it never re-parses the raw payload
    // or re-resolves the sender against state that may have changed.
    await db
      .insert(agentmailInboundTurns)
      .values({
        conversationId: conversation.id,
        webhookEventId: row.id,
        providerMessageId: message.message_id,
        providerTimestamp,
        senderEmail: senderAddress,
        senderUserId,
        bodyText: getAgentMailMessageBodyText(message).trim(),
      })
      .onConflictDoNothing({ target: agentmailInboundTurns.webhookEventId });

    await markEventProcessed(row.id);
    await addDrainJob(conversation.id, row.id);
  } catch (error) {
    await markEventFailed(row.id, error);
    throw error;
  }
}

type DrainableTurn = {
  turnId: string;
  providerMessageId: string;
  providerTimestamp: Date;
  senderUserId: string;
  senderEmail: string;
  bodyText: string;
  attempts: number;
  retryAt: Date | null;
};

async function getNextPendingTurn(
  conversationId: string,
): Promise<DrainableTurn | null> {
  const turn = await db.query.agentmailInboundTurns.findFirst({
    where: and(
      eq(agentmailInboundTurns.conversationId, conversationId),
      eq(agentmailInboundTurns.state, 'pending'),
    ),
    orderBy: [
      asc(agentmailInboundTurns.providerTimestamp),
      asc(agentmailInboundTurns.providerMessageId),
    ],
  });
  if (!turn) return null;

  return {
    turnId: turn.id,
    providerMessageId: turn.providerMessageId,
    providerTimestamp: turn.providerTimestamp,
    senderUserId: turn.senderUserId,
    senderEmail: turn.senderEmail,
    bodyText: turn.bodyText,
    attempts: turn.attempts,
    retryAt: turn.retryAt,
  };
}

async function markTurnConsumed(turnId: string) {
  await db
    .update(agentmailInboundTurns)
    .set({ state: 'consumed', consumedAt: new Date(), retryAt: null })
    .where(eq(agentmailInboundTurns.id, turnId));
}

async function markTurnParked(turnId: string, retryAt: Date) {
  await db
    .update(agentmailInboundTurns)
    .set({ retryAt })
    .where(eq(agentmailInboundTurns.id, turnId));
}

/**
 * Count a delivery failure against the turn. Past the cap the turn becomes a
 * dead letter (`failed`) so the conversation's later emails are no longer
 * stuck behind it, and the sender is told once, best effort.
 */
async function recordTurnFailure(
  turn: DrainableTurn,
  conversation: AgentMailConversationRow,
  error: unknown,
): Promise<'retry' | 'dead_letter'> {
  const attempts = turn.attempts + 1;
  const deadLetter = attempts >= FAILED_TURN_ATTEMPT_CAP;
  const lastError = error instanceof Error ? error.message : String(error);
  await db
    .update(agentmailInboundTurns)
    .set({
      attempts,
      lastError,
      retryAt: null,
      ...(deadLetter ? { state: 'failed' as const } : {}),
    })
    .where(eq(agentmailInboundTurns.id, turn.turnId));
  if (!deadLetter) {
    return 'retry';
  }

  console.error(
    `${LOG_PREFIX} Giving up on inbound turn ${turn.turnId} (message ${turn.providerMessageId}) after ${attempts} attempts: ${lastError}`,
  );
  await notifyTurnDeadLetter(turn, conversation).catch((notifyError) => {
    console.warn(
      `${LOG_PREFIX} Could not notify ${turn.senderEmail} that message ${turn.providerMessageId} failed: ${notifyError instanceof Error ? notifyError.message : String(notifyError)}`,
    );
  });
  return 'dead_letter';
}

async function notifyTurnDeadLetter(
  turn: DrainableTurn,
  conversation: AgentMailConversationRow,
): Promise<void> {
  const credentials = await resolveAgentMailRuntimeCredentials();
  if (!credentials.apiKey) return;
  const client = new AgentMailApiClient({ apiKey: credentials.apiKey });
  const text =
    'Roomote could not process this email after several attempts. Please try again later, or reach the Roomote administrator for your deployment if it keeps failing.';
  await client.replyToMessage(
    conversation.inboxId,
    turn.providerMessageId,
    { text, html: `<div><p>${escapeAgentMailHtml(text)}</p></div>` },
    { idempotencyKey: `agentmail:turn-failed:${turn.providerMessageId}` },
  );
}

async function tryClaimPendingInputAnswer(input: {
  conversation: AgentMailConversationRow;
  senderUserId: string;
  bodyText: string;
  activeRunId: number;
}): Promise<boolean> {
  const pendingRequest = await getPendingCommunicationRequestUserInput(
    'agentmail',
    input.conversation.id,
  );
  if (!pendingRequest || pendingRequest.runId !== input.activeRunId) {
    return false;
  }
  if (pendingRequest.status === 'submitted') {
    return false;
  }

  const parsedReply = parseAcpRequestUserInputAnswerReply(
    pendingRequest.questions,
    input.bodyText,
  );
  if (!parsedReply) {
    return false;
  }

  const cancelled = parsedReply.resolution === 'cancelled';
  return setTrustedRunActingUserOnSuccess({
    runId: input.activeRunId,
    userId: input.senderUserId,
    operation: async () =>
      submitPendingCommunicationRequestUserInputAnswer(
        'agentmail',
        input.conversation.id,
        pendingRequest,
        {
          answers: cancelled ? {} : parsedReply.answers,
          userId: input.senderUserId,
          timestamp: Date.now(),
        },
      ),
  });
}

/**
 * Email requests often live in the subject line ("what time is it" over an
 * empty or one-word body), so the agent-visible turn text carries both. The
 * raw body stays separate for answer parsing, where a prepended subject
 * would corrupt option matching.
 */
function buildTurnQuestionText(
  turn: DrainableTurn,
  conversation: AgentMailConversationRow,
): string {
  const subject = conversation.subject?.trim();
  return subject ? `Subject: ${subject}\n\n${turn.bodyText}` : turn.bodyText;
}

type TurnDeliveryOutcome =
  | { outcome: 'delivered' }
  | { outcome: 'parked'; retryAt: Date };

class AgentMailDeliveryUnavailableError extends Error {
  constructor(conversationId: string) {
    super(
      `AgentMail conversation ${conversationId} has no delivery route (credentials missing?); leaving its turns pending.`,
    );
    this.name = 'AgentMailDeliveryUnavailableError';
  }
}

async function deliverTurn(
  turn: DrainableTurn,
  conversation: AgentMailConversationRow,
  turnLock: FastAgentTurnLockHandle,
): Promise<TurnDeliveryOutcome> {
  // The reply route (in-reply-to, recipient) is read from the conversation
  // row when the reply is sent, so it is advanced here, for the turn about
  // to be answered, rather than when the email arrived: a later email from
  // a cc'd participant must not redirect the answer to this one.
  await advanceAgentMailInboundAnchor({
    conversationId: conversation.id,
    messageId: turn.providerMessageId,
    providerTimestamp: turn.providerTimestamp,
    senderEmail: turn.senderEmail,
    senderUserId: turn.senderUserId,
  });

  if (!turn.bodyText && !conversation.subject?.trim()) {
    return { outcome: 'delivered' };
  }

  const activeRun = await findActiveCommunicationTaskRun({
    provider: 'agentmail',
    channelId: conversation.inboxId,
    threadId: conversation.id,
  });

  if (activeRun) {
    const claimed = await tryClaimPendingInputAnswer({
      conversation,
      senderUserId: turn.senderUserId,
      bodyText: turn.bodyText,
      activeRunId: activeRun.id,
    });
    if (claimed) {
      return { outcome: 'delivered' };
    }

    // Follow-up to the active delegated run through the provider-generic
    // queue. queueCommunicationMessageOnce is idempotent on the message ts,
    // so a crash-and-retry of this turn cannot double-queue.
    await queueCommunicationMessageOnce('agentmail', activeRun.id, {
      provider: 'agentmail',
      text: buildTurnQuestionText(turn, conversation),
      user: turn.senderEmail,
      userId: turn.senderUserId,
      ts: turn.providerMessageId,
      channel: conversation.inboxId,
      threadTs: conversation.id,
      turnPolicy: { reactionsAllowed: false },
    });
    await setLatestInboundMessageId(
      'agentmail',
      activeRun.id,
      turn.providerMessageId,
    ).catch(() => undefined);
    return { outcome: 'delivered' };
  }

  const fastConversation = buildAgentMailFastConversation(conversation);
  const session = await getOrCreateFastAgentSession({
    userId: conversation.ownerUserId,
    conversation: fastConversation,
  });

  const result = await continueFastAgentSurfaceReplyWithLock(
    {
      sessionId: session.id,
      userId: turn.senderUserId,
      senderDisplayName: turn.senderEmail,
      question: buildTurnQuestionText(turn, conversation),
      currentMessageId: turn.providerMessageId,
    },
    turnLock,
  );
  switch (result.outcome) {
    case 'delivered':
      return { outcome: 'delivered' };
    case 'settled':
      // The queue already resumed and delivered (or retired) this turn after
      // an interruption; the inbound row is consumed without a second run.
      console.info(
        `${LOG_PREFIX} Inbound turn for message ${turn.providerMessageId} already settled durably; not re-running it`,
      );
      return { outcome: 'delivered' };
    case 'parked':
      return { outcome: 'parked', retryAt: result.retryAt };
    case 'unroutable':
      throw new AgentMailDeliveryUnavailableError(conversation.id);
  }
}

/**
 * Drain one conversation's admitted turns in provider order under one Fast
 * turn lock, mirroring `drainFastAgentParentEvents`. The Fast turn lock only
 * serializes concurrent turns; this ordered drain is what guarantees two
 * rapid emails run in arrival order. A busy conversation throws
 * `AgentMailConversationBusyError` so BullMQ delays and retries without
 * parking a worker slot.
 */
export async function drainAgentMailInboundTurns(
  conversationId: string,
): Promise<void> {
  if (!isEmailChannelEnabled()) {
    return;
  }
  const first = await getNextPendingTurn(conversationId);
  if (!first) return;

  // No credentials, no delivery route: leave every turn pending (the sweep
  // re-arms the drain) rather than consuming emails nothing can answer.
  const credentials = await resolveAgentMailRuntimeCredentials();
  if (!credentials.apiKey) {
    console.warn(
      `${LOG_PREFIX} AgentMail credentials are not configured; leaving conversation ${conversationId} pending`,
    );
    return;
  }

  const conversation = await db.query.agentmailConversations.findFirst({
    where: eq(agentmailConversations.id, conversationId),
  });
  if (!conversation) {
    return;
  }

  const turnLock = await acquireFastAgentTurnLock({
    conversation: buildAgentMailFastConversation(conversation),
    maxWaitMs: 0,
  });
  if (!turnLock) {
    throw new AgentMailConversationBusyError();
  }

  try {
    let turn: DrainableTurn | null = first;
    while (turn) {
      if (turn.retryAt && turn.retryAt.getTime() > Date.now()) {
        // Parked for a durable inference retry: hold the conversation, in
        // order, until it is due. Running the next email now would
        // supersede the parked turn and silently drop this one.
        await scheduleDrainAfterRetry(conversationId, turn.retryAt);
        return;
      }

      let delivery: TurnDeliveryOutcome;
      try {
        delivery = await deliverTurn(turn, conversation, turnLock);
      } catch (error) {
        if (error instanceof AgentMailDeliveryUnavailableError) {
          console.warn(`${LOG_PREFIX} ${error.message}`);
          return;
        }
        const disposition = await recordTurnFailure(turn, conversation, error);
        if (disposition === 'dead_letter') {
          turn = await getNextPendingTurn(conversationId);
          continue;
        }
        throw error;
      }

      if (delivery.outcome === 'parked') {
        await markTurnParked(turn.turnId, delivery.retryAt);
        await scheduleDrainAfterRetry(conversationId, delivery.retryAt);
        return;
      }
      // Consumed only after delivery: a crash mid-turn leaves the row
      // pending and the sweeper re-triggers the drain. Delivery is
      // idempotent (queueCommunicationMessageOnce; a Fast turn whose durable
      // row already settled is skipped, not re-run).
      await markTurnConsumed(turn.turnId);
      turn = await getNextPendingTurn(conversationId);
    }
  } finally {
    await turnLock().catch(() => {});
  }
}

/**
 * Recovery sweep: re-dispatch webhook events stranded between insert and
 * enqueue (`received`), events whose queued job was pruned before starting
 * (`queued`/`processing`), events whose processing failed transiently
 * (`failed`, until the attempt cap — only then is a row a true dead letter),
 * and conversations with pending turns whose drain wakeup was lost. Runs on
 * BullMQ startup and on a schedule. Staleness is measured against a
 * Node-side cutoff, like every other timestamp comparison in the codebase:
 * these columns are written from Node, so comparing them with the database's
 * `now()` would drift by the session time zone offset. Disabled channels do
 * nothing here: the gated processors leave rows untouched, so re-dispatching
 * them would only churn the queue every minute.
 */
export async function recoverPendingAgentMailWork(): Promise<number> {
  if (!isEmailChannelEnabled()) {
    return 0;
  }
  const staleBefore = new Date(Date.now() - RECOVERY_STALE_AFTER_MS);
  const staleEvents = await db
    .select({ deliveryId: agentmailWebhookEvents.deliveryId })
    .from(agentmailWebhookEvents)
    .where(
      and(
        sql`(
          ${agentmailWebhookEvents.state} in ('received', 'queued', 'processing')
          or (${agentmailWebhookEvents.state} = 'failed'
              and ${agentmailWebhookEvents.attempts} < ${FAILED_EVENT_ATTEMPT_CAP})
        )`,
        lt(agentmailWebhookEvents.updatedAt, staleBefore),
      ),
    )
    .orderBy(asc(agentmailWebhookEvents.receivedAt))
    .limit(RECOVERY_SWEEP_BATCH_SIZE);

  for (const event of staleEvents) {
    await addProcessJob(event.deliveryId);
  }

  const pendingTurnConversations = await db
    .selectDistinct({ conversationId: agentmailInboundTurns.conversationId })
    .from(agentmailInboundTurns)
    .where(
      and(
        eq(agentmailInboundTurns.state, 'pending'),
        lt(agentmailInboundTurns.createdAt, staleBefore),
        // A parked turn already has its own wakeup at its retry time.
        or(
          isNull(agentmailInboundTurns.retryAt),
          lte(agentmailInboundTurns.retryAt, new Date()),
        ),
      ),
    )
    .limit(RECOVERY_SWEEP_BATCH_SIZE);

  for (const row of pendingTurnConversations) {
    // Stable per-conversation sweep id: while a conversation stays pending
    // (e.g. busy in a long Fast turn) repeated sweeps must not mint a new
    // job each minute; the next sweep re-arms after the previous job ends.
    await addDrainJob(row.conversationId, 'sweep');
  }

  return staleEvents.length + pendingTurnConversations.length;
}
