import { unstable_cache } from 'next/cache';
import {
  generateTrackedNonTaskObject,
  NON_TASK_INFERENCE_SURFACES,
} from '@roomote/cloud-agents/server/non-task-provider-usage';
import { ACP_ENVELOPE_EVENT_TYPES } from '@roomote/types';
import { z } from 'zod';

// Maximum number of recent messages included in the suggestion prompt.
// History queries bound their fetches to this too, so long conversations
// never load their full transcript for a suggestion.
export const MAX_SUGGESTION_HISTORY_MESSAGES = 60;

// Maximum character count for the conversation text.
const MAX_CONVERSATION_CHARS = 60_000;

// Minimum number of conversational messages before suggesting anything.
const MIN_MESSAGES_FOR_SUGGESTION = 2;

// Cache TTL: 1 day in seconds. Active conversations naturally roll to fresh
// cache keys as each completed agent turn advances the assistant count.
const CACHE_TTL_SECONDS = 24 * 60 * 60;

const MAX_SUGGESTION_CHARS = 100;

// The prompt asks for 5-10 words; discard overshoots instead of truncating
// them mid-thought.
const MAX_SUGGESTION_WORDS = 12;

const composerSuggestionSchema = z.object({
  suggestion: z.string().trim().min(1).max(300).nullable(),
});

const SUGGESTION_PROMPT = `You suggest the next message a user might send to Roomote, an AI coding agent, in an ongoing task conversation.

Propose ONE short follow-up message the user is likely to want to send next, but only when the conversation points to a clear, high-value next step.

Rules:
- If you are not fairly confident about what the user would want next, set suggestion to null. Never pad with generic filler like "keep going" or "looks good".
- Keep it to 5-10 words, on a single line, with no surrounding quotes, markdown, or emoji.
- Write it in the user's voice, as an instruction or question addressed to the agent.
- Make it specific to this conversation (reference the actual work).
- Prefer a concrete next step: verifying the result, extending the change, covering a gap the agent mentioned, or shipping.

Here is the conversation:
`;

const SUGGESTABLE_EVENT_TYPES = new Set<string>([
  ACP_ENVELOPE_EVENT_TYPES.UserPrompt,
  ACP_ENVELOPE_EVENT_TYPES.AssistantMessage,
]);

/** The minimal message shape the suggestion prompt is built from; both task
 * envelopes and fast-session rows reduce to it. */
type SuggestableMessage = {
  /** Stable row id; the newest assistant id keys the generation cache. */
  id?: string | number;
  eventType: string;
  role?: string | null;
  text?: string | null;
};

function getSuggestableMessages<T extends SuggestableMessage>(
  messages: T[],
): T[] {
  return messages
    .filter((m) => m.text && m.text.trim().length > 0)
    .filter((m) => SUGGESTABLE_EVENT_TYPES.has(m.eventType))
    .slice(-MAX_SUGGESTION_HISTORY_MESSAGES);
}

/**
 * Build the transcript newest-last while trimming from the oldest end, so the
 * most recent turns always survive the character budget.
 */
function buildConversationText(messages: SuggestableMessage[]): string {
  const lines: string[] = [];
  let totalChars = 0;

  for (let i = messages.length - 1; i >= 0; i--) {
    const message = messages[i]!;
    const lineText = message.text?.trim();

    if (!lineText) {
      continue;
    }

    const speaker = message.role === 'user' ? 'User' : 'Roomote';
    const line = `${speaker}: ${lineText}\n\n`;

    if (totalChars + line.length > MAX_CONVERSATION_CHARS) {
      break;
    }

    lines.unshift(line);
    totalChars += line.length;
  }

  return lines.join('');
}

/** Collapse to one line, strip wrapping quotes, and enforce brevity. */
function normalizeSuggestion(raw: string | null): string | null {
  if (raw === null) {
    return null;
  }

  let text = raw.replace(/\s+/g, ' ').trim();

  if (
    text.length > 1 &&
    ((text.startsWith('"') && text.endsWith('"')) ||
      (text.startsWith("'") && text.endsWith("'")))
  ) {
    text = text.slice(1, -1).trim();
  }

  if (!text) {
    return null;
  }

  if (
    text.split(' ').length > MAX_SUGGESTION_WORDS ||
    text.length > MAX_SUGGESTION_CHARS
  ) {
    return null;
  }

  return text;
}

async function generateSuggestion(
  prompt: string,
  userId: string | null,
  taskId: string | null,
  fastConversationId: string | null,
): Promise<string | null> {
  const { object } = await generateTrackedNonTaskObject({
    userId,
    taskId,
    fastConversationId,
    surface: NON_TASK_INFERENCE_SURFACES.composerSuggestionGeneration,
    maxOutputTokens: 256,
    prompt,
    schema: composerSuggestionSchema,
  });

  return object.suggestion;
}

export type ComposerSuggestionResult = {
  suggestion: string | null;
  messageCount: number;
};

/**
 * Suggest the user's likely next composer message from a conversation's
 * persisted user/assistant history, generated by the deployment helper model.
 * `cacheScope` isolates the generation cache per conversation (task or
 * session); viewers of the same conversation share one cached generation per
 * history bucket. Fails soft: any error returns a null suggestion so the
 * composer is never blocked.
 */
export async function suggestNextComposerMessage({
  messages,
  cacheScope,
  userId,
  taskId = null,
  fastConversationId = null,
}: {
  messages: SuggestableMessage[];
  cacheScope: string;
  userId: string | null;
  taskId?: string | null;
  fastConversationId?: string | null;
}): Promise<ComposerSuggestionResult> {
  let messageCount = 0;

  try {
    const suggestable = getSuggestableMessages(messages);
    messageCount = suggestable.length;

    if (messageCount < MIN_MESSAGES_FOR_SUGGESTION) {
      return { suggestion: null, messageCount };
    }

    const conversationText = buildConversationText(suggestable);
    // One generation per completed agent turn: only a new assistant message
    // mints a fresh cache key, so user messages sent mid-turn keep reusing
    // (and, client-side, keep hiding) the previous suggestion. The newest
    // assistant id keys the cache rather than a count: history fetches are
    // bounded, so a within-window count would stop advancing once the
    // conversation outgrows the window.
    const assistantMessages = suggestable.filter(
      (m) => m.eventType === ACP_ENVELOPE_EVENT_TYPES.AssistantMessage,
    );
    const newestAssistant = assistantMessages.at(-1);
    const generationKey = String(
      newestAssistant?.id ?? assistantMessages.length,
    );

    const generator = unstable_cache(
      (prompt: string) =>
        generateSuggestion(prompt, userId, taskId, fastConversationId),
      ['composer-suggestion', cacheScope, generationKey],
      {
        revalidate: CACHE_TTL_SECONDS,
        tags: [`composer-suggestion:${cacheScope}`],
      },
    );

    const suggestion = await generator(SUGGESTION_PROMPT + conversationText);

    return { suggestion: normalizeSuggestion(suggestion), messageCount };
  } catch (error) {
    console.error('Error generating composer suggestion:', error);
    return { suggestion: null, messageCount };
  }
}
