import { unstable_cache } from 'next/cache';
import {
  generateTrackedNonTaskObject,
  NON_TASK_INFERENCE_SURFACES,
} from '@roomote/cloud-agents/server/non-task-provider-usage';
import { ACP_ENVELOPE_EVENT_TYPES } from '@roomote/types';
import { z } from 'zod';

import type { UserAuthSuccess, TaskMessageEnvelope } from '@/types';

import { getTaskMessageEnvelopes } from '@/lib/server';

// Maximum number of recent messages included in the suggestion prompt.
const MAX_MESSAGES = 60;

// Maximum character count for the conversation text.
const MAX_CONVERSATION_CHARS = 60_000;

// Minimum number of conversational messages before suggesting anything.
const MIN_MESSAGES_FOR_SUGGESTION = 2;

// Regenerate only after this many new conversational messages. Keys the
// generation cache so mid-turn polling reuses the previous suggestion.
const REGENERATION_THRESHOLD = 4;

// Cache TTL: 1 day in seconds. Active conversations naturally roll to fresh
// cache keys as their message-count bucket advances.
const CACHE_TTL_SECONDS = 24 * 60 * 60;

const MAX_SUGGESTION_CHARS = 200;

const composerSuggestionSchema = z.object({
  suggestion: z.string().trim().min(1).max(300),
});

const SUGGESTION_PROMPT = `You suggest the next message a user might send to Roomote, an AI coding agent, in an ongoing task conversation.

Propose ONE short follow-up message the user is likely to want to send next.

Rules:
- Write it in the user's voice, as an instruction or question addressed to the agent.
- Keep it under 140 characters, on a single line, with no surrounding quotes, markdown, or emoji.
- Make it specific to this conversation (reference the actual work), never generic filler.
- Prefer a concrete next step: verifying the result, extending the change, covering a gap the agent mentioned, or shipping.

Here is the conversation:
`;

const SUGGESTABLE_EVENT_TYPES = new Set<string>([
  ACP_ENVELOPE_EVENT_TYPES.UserPrompt,
  ACP_ENVELOPE_EVENT_TYPES.AssistantMessage,
]);

function getSuggestableMessages(
  messages: TaskMessageEnvelope[],
): TaskMessageEnvelope[] {
  return messages
    .filter((m) => m.text && m.text.trim().length > 0)
    .filter((m) => SUGGESTABLE_EVENT_TYPES.has(m.eventType))
    .slice(-MAX_MESSAGES);
}

/**
 * Build the transcript newest-last while trimming from the oldest end, so the
 * most recent turns always survive the character budget.
 */
function buildConversationText(messages: TaskMessageEnvelope[]): string {
  const lines: string[] = [];
  let totalChars = 0;

  for (let i = messages.length - 1; i >= 0; i--) {
    const message = messages[i]!;
    const lineText = message.text?.trim();

    if (!lineText) {
      continue;
    }

    const speaker = message.role === 'user' ? 'User' : 'Roomote';
    const line = `${speaker}: ${lineText}\n\n`;

    if (totalChars + line.length > MAX_CONVERSATION_CHARS) {
      break;
    }

    lines.unshift(line);
    totalChars += line.length;
  }

  return lines.join('');
}

/** Collapse to one line, strip wrapping quotes, and cap the length. */
function normalizeSuggestion(raw: string): string | null {
  let text = raw.replace(/\s+/g, ' ').trim();

  if (
    text.length > 1 &&
    ((text.startsWith('"') && text.endsWith('"')) ||
      (text.startsWith("'") && text.endsWith("'")))
  ) {
    text = text.slice(1, -1).trim();
  }

  if (!text) {
    return null;
  }

  return text.length > MAX_SUGGESTION_CHARS
    ? `${text.slice(0, MAX_SUGGESTION_CHARS - 1).trimEnd()}\u2026`
    : text;
}

async function generateSuggestion(
  prompt: string,
  userId: string | null,
  taskId: string,
): Promise<string> {
  const { object } = await generateTrackedNonTaskObject({
    userId,
    taskId,
    surface: NON_TASK_INFERENCE_SURFACES.composerSuggestionGeneration,
    maxOutputTokens: 256,
    prompt,
    schema: composerSuggestionSchema,
  });

  return object.suggestion;
}

type ComposerSuggestionResult = {
  suggestion: string | null;
  messageCount: number;
};

/**
 * Suggest the user's likely next composer message for a task, generated by
 * the deployment helper model from the persisted task conversation. Fails
 * soft: any error returns a null suggestion so the composer is never blocked.
 */
export async function getComposerSuggestionCommand(
  auth: UserAuthSuccess,
  input: { taskId: string },
): Promise<ComposerSuggestionResult> {
  let messageCount = 0;

  try {
    const messages = await getTaskMessageEnvelopes({ taskId: input.taskId });
    const suggestable = getSuggestableMessages(messages);
    messageCount = suggestable.length;

    if (messageCount < MIN_MESSAGES_FOR_SUGGESTION) {
      return { suggestion: null, messageCount };
    }

    const conversationText = buildConversationText(suggestable);
    const bucketedCount =
      Math.floor(messageCount / REGENERATION_THRESHOLD) *
      REGENERATION_THRESHOLD;

    // Suggestions are task-scoped, so viewers of the same task share one
    // cached generation per history bucket.
    const generator = unstable_cache(
      (prompt: string) =>
        generateSuggestion(prompt, auth.userId ?? null, input.taskId),
      ['composer-suggestion', input.taskId, String(bucketedCount)],
      {
        revalidate: CACHE_TTL_SECONDS,
        tags: [`composer-suggestion:${input.taskId}`],
      },
    );

    const suggestion = await generator(SUGGESTION_PROMPT + conversationText);

    return { suggestion: normalizeSuggestion(suggestion), messageCount };
  } catch (error) {
    console.error('Error generating composer suggestion:', error);
    return { suggestion: null, messageCount };
  }
}
