import type { UserAuthSuccess } from '@/types';

import { getTaskMessageEnvelopes } from '@/lib/server';
import {
  type ComposerSuggestionResult,
  suggestNextComposerMessage,
} from '@/lib/server/composer-suggestion';

/**
 * Suggest the user's likely next composer message for a task, generated by
 * the deployment helper model from the persisted task conversation. Fails
 * soft: any error returns a null suggestion so the composer is never blocked.
 */
export async function getComposerSuggestionCommand(
  auth: UserAuthSuccess,
  input: { taskId: string },
): Promise<ComposerSuggestionResult> {
  try {
    const messages = await getTaskMessageEnvelopes({ taskId: input.taskId });

    return await suggestNextComposerMessage({
      messages,
      cacheScope: `task:${input.taskId}`,
      userId: auth.userId ?? null,
      taskId: input.taskId,
    });
  } catch (error) {
    console.error('Error loading task history for composer suggestion:', error);
    return { suggestion: null, messageCount: 0 };
  }
}
