import {
  TASK_RUNTIME_FAILURE_TEXT,
  TASK_STARTUP_FAILURE_TEXT,
} from '@roomote/communication/chat-messages';

export const SLACK_STARTUP_FAILURE_TEXT = TASK_STARTUP_FAILURE_TEXT;
export const SLACK_RUNTIME_FAILURE_TEXT = TASK_RUNTIME_FAILURE_TEXT;
