WITH env_var_renames(old_name, new_name, priority) AS (
  VALUES
    ('ROOMOTE_APP_URL', 'R_APP_URL', 10),
    ('ROOMOTE_PUBLIC_URL', 'R_PUBLIC_URL', 10),
    ('ROOMOTE_APP_ENV', 'R_APP_ENV', 10),
    ('ROOMOTE_ALLOWED_EMAILS', 'R_ALLOWED_EMAILS', 10),
    ('ROOMOTE_MODEL', 'R_MODEL', 10),
    ('ROOMOTE_SMALL_MODEL', 'R_SMALL_MODEL', 10),
    ('ROOMOTE_VISION_MODEL', 'R_VISION_MODEL', 10),
    ('ROOMOTE_CODE_REVIEW_MODEL', 'R_CODE_REVIEW_MODEL', 10),
    ('ROOMOTE_EXPLORE_MODEL', 'R_EXPLORE_MODEL', 10),
    ('ROOMOTE_PLANNING_MODEL', 'R_PLANNING_MODEL', 10),
    ('ROOMOTE_MODEL_REASONING_EFFORT', 'R_MODEL_REASONING_EFFORT', 10),
    ('ROOMOTE_SMALL_MODEL_REASONING_EFFORT', 'R_SMALL_MODEL_REASONING_EFFORT', 10),
    ('ROOMOTE_VISION_MODEL_REASONING_EFFORT', 'R_VISION_MODEL_REASONING_EFFORT', 10),
    ('ROOMOTE_CODE_REVIEW_MODEL_REASONING_EFFORT', 'R_CODE_REVIEW_MODEL_REASONING_EFFORT', 10),
    ('ROOMOTE_EXPLORE_MODEL_REASONING_EFFORT', 'R_EXPLORE_MODEL_REASONING_EFFORT', 10),
    ('ROOMOTE_PLANNING_MODEL_REASONING_EFFORT', 'R_PLANNING_MODEL_REASONING_EFFORT', 10),
    ('ROOMOTE_MODEL_ENV_KEYS', 'R_MODEL_ENV_KEYS', 10),
    ('ROOMOTE_AUTH_SLACK_CLIENT_ID', 'R_SLACK_CLIENT_ID', 10),
    ('SLACK_CLIENT_ID', 'R_SLACK_CLIENT_ID', 20),
    ('ROOMOTE_AUTH_SLACK_CLIENT_SECRET', 'R_SLACK_CLIENT_SECRET', 10),
    ('SLACK_CLIENT_SECRET', 'R_SLACK_CLIENT_SECRET', 20),
    ('SLACK_SIGNING_SECRET', 'R_SLACK_SIGNING_SECRET', 10),
    ('ROOMOTE_AUTH_MICROSOFT_CLIENT_ID', 'R_MICROSOFT_CLIENT_ID', 10),
    ('ROOMOTE_AUTH_MICROSOFT_CLIENT_SECRET', 'R_MICROSOFT_CLIENT_SECRET', 10),
    ('ROOMOTE_AUTH_MICROSOFT_TENANT_ID', 'R_MICROSOFT_TENANT_ID', 10),
    ('TEAMS_BOT_APP_ID', 'R_TEAMS_BOT_APP_ID', 10),
    ('TEAMS_BOT_APP_PASSWORD', 'R_TEAMS_BOT_APP_PASSWORD', 10),
    ('TEAMS_BOT_TENANT_ID', 'R_TEAMS_BOT_TENANT_ID', 10),
    ('TEAMS_BOT_NAME', 'R_TEAMS_BOT_NAME', 10),
    ('TEAMS_BOT_TOKEN_ENDPOINT', 'R_TEAMS_BOT_TOKEN_ENDPOINT', 10),
    ('TEAMS_BOT_OAUTH_SCOPE', 'R_TEAMS_BOT_OAUTH_SCOPE', 10),
    ('NEXT_PUBLIC_GITHUB_APP_SLUG', 'R_GITHUB_APP_SLUG', 10),
    ('GITHUB_APP_SLUG', 'R_GITHUB_APP_SLUG', 20),
    ('GITHUB_APP_ID', 'R_GITHUB_APP_ID', 10),
    ('GITHUB_APP_PRIVATE_KEY', 'R_GITHUB_APP_PRIVATE_KEY', 10),
    ('GITHUB_CLIENT_ID', 'R_GITHUB_CLIENT_ID', 10),
    ('GITHUB_CLIENT_SECRET', 'R_GITHUB_CLIENT_SECRET', 10),
    ('GITHUB_WEBHOOK_SECRET', 'R_GITHUB_WEBHOOK_SECRET', 10)
)
DELETE FROM "environment_variables" legacy
USING env_var_renames rename
WHERE legacy."name" = rename.old_name
  AND EXISTS (
    SELECT 1
    FROM "environment_variables" canonical
    WHERE canonical."name" = rename.new_name
  );

WITH env_var_renames(old_name, new_name, priority) AS (
  VALUES
    ('ROOMOTE_APP_URL', 'R_APP_URL', 10),
    ('ROOMOTE_PUBLIC_URL', 'R_PUBLIC_URL', 10),
    ('ROOMOTE_APP_ENV', 'R_APP_ENV', 10),
    ('ROOMOTE_ALLOWED_EMAILS', 'R_ALLOWED_EMAILS', 10),
    ('ROOMOTE_MODEL', 'R_MODEL', 10),
    ('ROOMOTE_SMALL_MODEL', 'R_SMALL_MODEL', 10),
    ('ROOMOTE_VISION_MODEL', 'R_VISION_MODEL', 10),
    ('ROOMOTE_CODE_REVIEW_MODEL', 'R_CODE_REVIEW_MODEL', 10),
    ('ROOMOTE_EXPLORE_MODEL', 'R_EXPLORE_MODEL', 10),
    ('ROOMOTE_PLANNING_MODEL', 'R_PLANNING_MODEL', 10),
    ('ROOMOTE_MODEL_REASONING_EFFORT', 'R_MODEL_REASONING_EFFORT', 10),
    ('ROOMOTE_SMALL_MODEL_REASONING_EFFORT', 'R_SMALL_MODEL_REASONING_EFFORT', 10),
    ('ROOMOTE_VISION_MODEL_REASONING_EFFORT', 'R_VISION_MODEL_REASONING_EFFORT', 10),
    ('ROOMOTE_CODE_REVIEW_MODEL_REASONING_EFFORT', 'R_CODE_REVIEW_MODEL_REASONING_EFFORT', 10),
    ('ROOMOTE_EXPLORE_MODEL_REASONING_EFFORT', 'R_EXPLORE_MODEL_REASONING_EFFORT', 10),
    ('ROOMOTE_PLANNING_MODEL_REASONING_EFFORT', 'R_PLANNING_MODEL_REASONING_EFFORT', 10),
    ('ROOMOTE_MODEL_ENV_KEYS', 'R_MODEL_ENV_KEYS', 10),
    ('ROOMOTE_AUTH_SLACK_CLIENT_ID', 'R_SLACK_CLIENT_ID', 10),
    ('SLACK_CLIENT_ID', 'R_SLACK_CLIENT_ID', 20),
    ('ROOMOTE_AUTH_SLACK_CLIENT_SECRET', 'R_SLACK_CLIENT_SECRET', 10),
    ('SLACK_CLIENT_SECRET', 'R_SLACK_CLIENT_SECRET', 20),
    ('SLACK_SIGNING_SECRET', 'R_SLACK_SIGNING_SECRET', 10),
    ('ROOMOTE_AUTH_MICROSOFT_CLIENT_ID', 'R_MICROSOFT_CLIENT_ID', 10),
    ('ROOMOTE_AUTH_MICROSOFT_CLIENT_SECRET', 'R_MICROSOFT_CLIENT_SECRET', 10),
    ('ROOMOTE_AUTH_MICROSOFT_TENANT_ID', 'R_MICROSOFT_TENANT_ID', 10),
    ('TEAMS_BOT_APP_ID', 'R_TEAMS_BOT_APP_ID', 10),
    ('TEAMS_BOT_APP_PASSWORD', 'R_TEAMS_BOT_APP_PASSWORD', 10),
    ('TEAMS_BOT_TENANT_ID', 'R_TEAMS_BOT_TENANT_ID', 10),
    ('TEAMS_BOT_NAME', 'R_TEAMS_BOT_NAME', 10),
    ('TEAMS_BOT_TOKEN_ENDPOINT', 'R_TEAMS_BOT_TOKEN_ENDPOINT', 10),
    ('TEAMS_BOT_OAUTH_SCOPE', 'R_TEAMS_BOT_OAUTH_SCOPE', 10),
    ('NEXT_PUBLIC_GITHUB_APP_SLUG', 'R_GITHUB_APP_SLUG', 10),
    ('GITHUB_APP_SLUG', 'R_GITHUB_APP_SLUG', 20),
    ('GITHUB_APP_ID', 'R_GITHUB_APP_ID', 10),
    ('GITHUB_APP_PRIVATE_KEY', 'R_GITHUB_APP_PRIVATE_KEY', 10),
    ('GITHUB_CLIENT_ID', 'R_GITHUB_CLIENT_ID', 10),
    ('GITHUB_CLIENT_SECRET', 'R_GITHUB_CLIENT_SECRET', 10),
    ('GITHUB_WEBHOOK_SECRET', 'R_GITHUB_WEBHOOK_SECRET', 10)
),
ranked_legacy AS (
  SELECT
    env_var."id",
    row_number() OVER (
      PARTITION BY rename.new_name
      ORDER BY rename.priority ASC, env_var."updated_at" DESC, env_var."created_at" DESC, env_var."id" ASC
    ) AS duplicate_rank
  FROM "environment_variables" env_var
  JOIN env_var_renames rename
    ON env_var."name" = rename.old_name
)
DELETE FROM "environment_variables" duplicate
USING ranked_legacy ranked
WHERE duplicate."id" = ranked."id"
  AND ranked.duplicate_rank > 1;

WITH env_var_renames(old_name, new_name) AS (
  VALUES
    ('ROOMOTE_APP_URL', 'R_APP_URL'),
    ('ROOMOTE_PUBLIC_URL', 'R_PUBLIC_URL'),
    ('ROOMOTE_APP_ENV', 'R_APP_ENV'),
    ('ROOMOTE_ALLOWED_EMAILS', 'R_ALLOWED_EMAILS'),
    ('ROOMOTE_MODEL', 'R_MODEL'),
    ('ROOMOTE_SMALL_MODEL', 'R_SMALL_MODEL'),
    ('ROOMOTE_VISION_MODEL', 'R_VISION_MODEL'),
    ('ROOMOTE_CODE_REVIEW_MODEL', 'R_CODE_REVIEW_MODEL'),
    ('ROOMOTE_EXPLORE_MODEL', 'R_EXPLORE_MODEL'),
    ('ROOMOTE_PLANNING_MODEL', 'R_PLANNING_MODEL'),
    ('ROOMOTE_MODEL_REASONING_EFFORT', 'R_MODEL_REASONING_EFFORT'),
    ('ROOMOTE_SMALL_MODEL_REASONING_EFFORT', 'R_SMALL_MODEL_REASONING_EFFORT'),
    ('ROOMOTE_VISION_MODEL_REASONING_EFFORT', 'R_VISION_MODEL_REASONING_EFFORT'),
    ('ROOMOTE_CODE_REVIEW_MODEL_REASONING_EFFORT', 'R_CODE_REVIEW_MODEL_REASONING_EFFORT'),
    ('ROOMOTE_EXPLORE_MODEL_REASONING_EFFORT', 'R_EXPLORE_MODEL_REASONING_EFFORT'),
    ('ROOMOTE_PLANNING_MODEL_REASONING_EFFORT', 'R_PLANNING_MODEL_REASONING_EFFORT'),
    ('ROOMOTE_MODEL_ENV_KEYS', 'R_MODEL_ENV_KEYS'),
    ('SLACK_CLIENT_ID', 'R_SLACK_CLIENT_ID'),
    ('SLACK_CLIENT_SECRET', 'R_SLACK_CLIENT_SECRET'),
    ('SLACK_SIGNING_SECRET', 'R_SLACK_SIGNING_SECRET'),
    ('ROOMOTE_AUTH_SLACK_CLIENT_ID', 'R_SLACK_CLIENT_ID'),
    ('ROOMOTE_AUTH_SLACK_CLIENT_SECRET', 'R_SLACK_CLIENT_SECRET'),
    ('ROOMOTE_AUTH_MICROSOFT_CLIENT_ID', 'R_MICROSOFT_CLIENT_ID'),
    ('ROOMOTE_AUTH_MICROSOFT_CLIENT_SECRET', 'R_MICROSOFT_CLIENT_SECRET'),
    ('ROOMOTE_AUTH_MICROSOFT_TENANT_ID', 'R_MICROSOFT_TENANT_ID'),
    ('TEAMS_BOT_APP_ID', 'R_TEAMS_BOT_APP_ID'),
    ('TEAMS_BOT_APP_PASSWORD', 'R_TEAMS_BOT_APP_PASSWORD'),
    ('TEAMS_BOT_TENANT_ID', 'R_TEAMS_BOT_TENANT_ID'),
    ('TEAMS_BOT_NAME', 'R_TEAMS_BOT_NAME'),
    ('TEAMS_BOT_TOKEN_ENDPOINT', 'R_TEAMS_BOT_TOKEN_ENDPOINT'),
    ('TEAMS_BOT_OAUTH_SCOPE', 'R_TEAMS_BOT_OAUTH_SCOPE'),
    ('NEXT_PUBLIC_GITHUB_APP_SLUG', 'R_GITHUB_APP_SLUG'),
    ('GITHUB_APP_SLUG', 'R_GITHUB_APP_SLUG'),
    ('GITHUB_APP_ID', 'R_GITHUB_APP_ID'),
    ('GITHUB_APP_PRIVATE_KEY', 'R_GITHUB_APP_PRIVATE_KEY'),
    ('GITHUB_CLIENT_ID', 'R_GITHUB_CLIENT_ID'),
    ('GITHUB_CLIENT_SECRET', 'R_GITHUB_CLIENT_SECRET'),
    ('GITHUB_WEBHOOK_SECRET', 'R_GITHUB_WEBHOOK_SECRET')
)
UPDATE "environment_variables" env_var
SET "name" = rename.new_name,
    "updated_at" = now()
FROM env_var_renames rename
WHERE env_var."name" = rename.old_name;
