import { chmodSync, readFileSync, writeFileSync, existsSync } from 'fs';
import { homedir } from 'os';
import { join } from 'path';

import {
  buildPreviewProxyUrl,
  CODE_SERVER_NAMED_PORT,
  getSourceControlTokenEnvVars,
  portNameToSlug,
  PRODUCT_NAME,
  TASK_MODEL_ROLE_DESCRIPTORS,
  type SourceControlTokenMetadata,
} from '@roomote/types';
import { type TaskRun } from '@roomote/sdk/client';

import {
  applySourceControlTokenMetadata,
  ensureGhCliWrapper,
  ensureSourceControlTokenEnvFiles,
  COMMON_ENV_FILE_PATH,
  GH_TOKEN_ENV_FILE_PATH,
  GITLAB_TOKEN_ENV_FILE_PATH,
  GITEA_TOKEN_ENV_FILE_PATH,
  ADO_TOKEN_ENV_FILE_PATH,
} from '../../lib';
import { GH_CLI_WRAPPER_BIN_DIR } from '../../lib/github-token';

const ENV_VARS_START = `# BEGIN ${PRODUCT_NAME} environment variables`;
const ENV_VARS_END = `# END ${PRODUCT_NAME} environment variables`;

/** POSIX-compliant env var name: letters, digits, underscores; must not start with a digit. */
const VALID_ENV_VAR_NAME = /^[a-zA-Z_][a-zA-Z0-9_]*$/;

export const INHERITED_MODEL_RUNTIME_ENV_VAR_NAMES: ReadonlySet<string> =
  new Set([
    ...Object.values(TASK_MODEL_ROLE_DESCRIPTORS).flatMap((descriptor) => [
      descriptor.modelEnvVar,
      descriptor.reasoningEnvVar,
      `ROOMOTE_${descriptor.modelEnvVar.slice(2)}`,
      `ROOMOTE_${descriptor.reasoningEnvVar.slice(2)}`,
    ]),
    'R_MODEL_ENV_KEYS',
    'ROOMOTE_MODEL_ENV_KEYS',
  ]);

export function buildEnvironmentShellEnvVars(
  envVars: Record<string, string>,
  explicitEnvVarNames: Iterable<string> = [],
): Record<string, string> {
  const explicitNames = new Set(explicitEnvVarNames);

  return Object.fromEntries(
    Object.entries(envVars).filter(
      ([name]) =>
        explicitNames.has(name) ||
        !INHERITED_MODEL_RUNTIME_ENV_VAR_NAMES.has(name),
    ),
  );
}

/**
 * Returns true when `name` is a safe POSIX environment variable name.
 * Rejects names containing shell metacharacters that could lead to command
 * injection when interpolated into a shell export statement.
 */
export function isValidEnvVarName(name: string): boolean {
  return VALID_ENV_VAR_NAME.test(name);
}

/**
 * Build the shell export lines for the given env vars.
 * Skips source-control tokens (handled via provider token env files) and
 * invalid names.
 */
function buildExportLines(envVars: Record<string, string>): string[] {
  const lines: string[] = [];
  const sourceControlTokenEnvVars = new Set<string>(
    getSourceControlTokenEnvVars(),
  );

  for (const [key, value] of Object.entries(envVars)) {
    if (sourceControlTokenEnvVars.has(key) || key === 'PATH') {
      continue;
    }

    if (!isValidEnvVarName(key)) {
      console.warn(
        `[writeBashrc] Skipping invalid env var name: ${JSON.stringify(key)}`,
      );

      continue;
    }

    const escapedValue = String(value).replace(/'/g, "'\\''");
    lines.push(`export ${key}='${escapedValue}'`);
  }

  return lines;
}

/**
 * Write env vars to a standalone file (~/.roomote/env.sh) that is safe for both
 * BASH_ENV (non-interactive shells) and sourcing from .bashrc (interactive
 * shells).
 */
export function writeCommonEnvFile(envVars: Record<string, string>): void {
  const lines: string[] = [
    '#!/usr/bin/env bash',
    '# Auto-generated by the worker. Do not edit manually.',
    '',
    '# Guard against recursive sourcing (BASH_ENV + .bashrc both source this).',
    'if [ -n "$__ROOMOTE_ENV_LOADED" ]; then return 0 2>/dev/null || true; fi',
    'export __ROOMOTE_ENV_LOADED=1',
    '',
  ];

  const escapedWrapperDir = GH_CLI_WRAPPER_BIN_DIR.replace(/'/g, "'\\''");
  lines.push(
    `if [[ ":$PATH:" != *":${escapedWrapperDir}:"* ]]; then export PATH='${escapedWrapperDir}':"$PATH"; fi`,
  );
  lines.push('');
  lines.push(...buildExportLines(envVars));
  lines.push(
    '',
    `source '${GH_TOKEN_ENV_FILE_PATH}'`,
    `source '${GITLAB_TOKEN_ENV_FILE_PATH}'`,
    `source '${GITEA_TOKEN_ENV_FILE_PATH}'`,
    `source '${ADO_TOKEN_ENV_FILE_PATH}'`,
  );
  lines.push('', 'unset __ROOMOTE_ENV_LOADED', '');

  writeFileSync(COMMON_ENV_FILE_PATH, lines.join('\n'), { mode: 0o600 });
  chmodSync(COMMON_ENV_FILE_PATH, 0o600);
}

/**
 * Write environment variables to .bashrc in an idempotent marked section.
 */
export function writeBashrc(envVars: Record<string, string>): void {
  writeCommonEnvFile(envVars);

  const bashrcPath = join(homedir(), '.bashrc');

  let existingContent = '';

  if (existsSync(bashrcPath)) {
    existingContent = readFileSync(bashrcPath, 'utf-8');
  }

  const startIndex = existingContent.indexOf(ENV_VARS_START);
  const endIndex = existingContent.indexOf(ENV_VARS_END);

  if (startIndex !== -1 && endIndex !== -1 && endIndex > startIndex) {
    const afterEnd = existingContent.slice(endIndex + ENV_VARS_END.length);
    const trimmedAfter = afterEnd.startsWith('\n')
      ? afterEnd.slice(1)
      : afterEnd;

    existingContent = existingContent.slice(0, startIndex) + trimmedAfter;
  }

  const lines: string[] = [
    '',
    ENV_VARS_START,
    `source '${COMMON_ENV_FILE_PATH}'`,
    ENV_VARS_END,
    '',
  ];

  writeFileSync(bashrcPath, existingContent + lines.join('\n'));
}

interface PreviewIdentity {
  taskId: string;
  machineDomains: Record<string, string>;
  proxyPorts: Record<string, number>;
}

function resolvePreviewIdentity(taskRun?: TaskRun): PreviewIdentity | null {
  if (taskRun?.taskId && taskRun.machineDomains) {
    return {
      taskId: taskRun.taskId,
      machineDomains: taskRun.machineDomains,
      proxyPorts: taskRun.proxyPorts ?? {},
    };
  }

  if (taskRun?.machineDomains) {
    return {
      taskId: '',
      machineDomains: taskRun.machineDomains,
      proxyPorts: taskRun.proxyPorts ?? {},
    };
  }

  return null;
}

/**
 * Inject environment variables into the shell environment:
 * 1. Inject Roomote runtime auth-bypass values when available.
 * 2. Sync source-control auth state into the worker-managed token files and
 *    proxy config.
 * 3. Write env vars to the worker-managed shell env file so bash-driven
 *    commands load the gh wrapper without mutating the runtime PATH object.
 *
 * This function is idempotent - it removes any previous env var section before
 * writing the new one, preventing duplicates across snapshot restores.
 */
export async function injectEnvVars(
  envVars: Record<string, string>,
  taskRun?: TaskRun,
  options?: {
    previewProxyBaseUrl?: string;
    previewProxySubdomainSuffix?: string;
    sourceControlToken?: SourceControlTokenMetadata;
    syncSourceControlTokenFiles?: boolean;
    omitInheritedModelRuntimeEnvFromShell?: boolean;
    explicitShellEnvVars?: Record<string, string>;
  },
): Promise<void> {
  const identity = resolvePreviewIdentity(taskRun);
  const previewProxyBaseUrl =
    options?.previewProxyBaseUrl ?? process.env.PREVIEW_PROXY_BASE_URL;
  const previewProxySubdomainSuffix =
    options?.previewProxySubdomainSuffix ??
    process.env.PREVIEW_PROXY_SUBDOMAIN_SUFFIX;

  if (identity && identity.taskId && previewProxyBaseUrl) {
    for (const [name, domain] of Object.entries(identity.machineDomains)) {
      const envVarName = `ROOMOTE_${name}_HOST`;
      const previewUrlEnvVarName = `ROOMOTE_${name}_PREVIEW_URL`;
      const isProxied =
        name === CODE_SERVER_NAMED_PORT.name || name in identity.proxyPorts;
      const previewUrl = buildPreviewProxyUrl(
        identity.taskId,
        portNameToSlug(name),
        previewProxyBaseUrl,
        previewProxySubdomainSuffix,
      );

      // Keep *_HOST pointing at the direct machine domain for unproxied ports,
      // while also exposing the authenticated shareable URL that agents and
      // browser tooling must use to exercise the preview entrypoint itself.
      if (name === CODE_SERVER_NAMED_PORT.name) {
        delete envVars[previewUrlEnvVarName];
      } else {
        envVars[previewUrlEnvVarName] = previewUrl;
      }

      if (isProxied) {
        envVars[envVarName] = previewUrl;
      } else {
        envVars[envVarName] = domain;
      }
    }
  } else if (identity) {
    for (const [name, domain] of Object.entries(identity.machineDomains)) {
      envVars[`ROOMOTE_${name}_HOST`] = domain;
    }
  }

  // Dev servers running in the sandbox (e.g. Next.js) reject cross-origin
  // requests to internal dev resources (fonts, HMR, overlay assets) unless the
  // preview hostname is allowlisted; apps derive that allowlist from
  // PREVIEW_DOMAINS. Deployment env vars only include PREVIEW_DOMAINS when the
  // deployment persisted preview settings, so fall back to deriving it from
  // the preview-proxy base URL the worker already has. An explicit
  // deployment-provided value always wins.
  if (previewProxyBaseUrl && !envVars.PREVIEW_DOMAINS) {
    try {
      envVars.PREVIEW_DOMAINS = new URL(previewProxyBaseUrl).hostname;
    } catch {
      // Ignore invalid base URLs; preview host construction above would have
      // been skipped or failed for the same reason.
    }
  }

  const authBypassValue =
    process.env.ROOMOTE_AUTH_BYPASS_VALUE ?? taskRun?.authBypassValue;
  if (authBypassValue) {
    envVars.ROOMOTE_AUTH_BYPASS_VALUE = authBypassValue;
  }

  const authBypassHeaderName =
    process.env.ROOMOTE_AUTH_BYPASS_HEADER_NAME ??
    taskRun?.authBypassHeaderName;
  if (authBypassHeaderName) {
    envVars.ROOMOTE_AUTH_BYPASS_HEADER_NAME = authBypassHeaderName;
  }

  ensureSourceControlTokenEnvFiles();
  ensureGhCliWrapper();
  envVars.BASH_ENV = COMMON_ENV_FILE_PATH;
  if (options?.syncSourceControlTokenFiles !== false) {
    await applySourceControlTokenMetadata(
      options?.sourceControlToken ?? { envVars },
    );
  }

  writeBashrc(
    options?.omitInheritedModelRuntimeEnvFromShell
      ? buildEnvironmentShellEnvVars(
          { ...envVars, ...options.explicitShellEnvVars },
          Object.keys(options.explicitShellEnvVars ?? {}),
        )
      : envVars,
  );
}
