interface ParsedHost {
  portName: string;
  taskId: string | null;
  isValid: boolean;
}

interface ParsedNestedHost {
  /** The outer task ID */
  outerTaskId: string | null;
  /** Port name for the outer sandbox */
  outerPortName: string;
  /** Prefix (inner portion) of the subdomain, before the outer ID */
  innerPrefix: string;
  isValid: boolean;
}

// Generated taskId format: fixed 13-char lowercase base36
const TASK_ID_REGEX = /^[0-9a-z]{13}$/;

// Port name validation: alphanumeric and hyphens only
const PORT_NAME_REGEX = /^[a-z0-9-]+$/;

/**
 * Parses a preview proxy host to extract taskId and portName.
 *
 * URL format: {taskId}-{portName}.{any-domain}
 * Example: 20imtw24sm6hv-web.preview.roomote.run
 *
 * Task IDs are 13-character base36 strings generated by generateTaskId().
 *
 * Domain validation is NOT performed here. The main app's /api/auth/preview
 * endpoint validates redirect_uri against PREVIEW_DOMAINS for security.
 */
export function parseHost(host: string): ParsedHost {
  const invalid: ParsedHost = { portName: '', taskId: null, isValid: false };

  // Extract subdomain (everything before the first dot)
  const dotIndex = host.indexOf('.');

  if (dotIndex === -1) {
    return invalid;
  }

  const subdomain = host.substring(0, dotIndex);

  const firstHyphen = subdomain.indexOf('-');

  if (firstHyphen >= 0) {
    const potentialTaskId = subdomain.substring(0, firstHyphen);
    const portName = subdomain.substring(firstHyphen + 1);

    if (TASK_ID_REGEX.test(potentialTaskId) && portName) {
      const normalizedPortName = portName.toLowerCase();

      if (PORT_NAME_REGEX.test(normalizedPortName)) {
        return {
          portName: normalizedPortName,
          taskId: potentialTaskId,
          isValid: true,
        };
      }
    }
  }

  return invalid;
}

/**
 * Parse a host with a known suffix to strip.
 * Used by inner preview-proxies to remove the outer taskId+port suffix
 * from nested hostnames before delegating to the normal `parseHost()`.
 *
 * Example:
 *   host = "20imtw24sm6hv-web-r4nje6w8ab123-preview.preview.roomote.run"
 *   suffix = "r4nje6w8ab123-preview"
 *   → strips to "20imtw24sm6hv-web.preview.roomote.run"
 *   → delegates to parseHost()
 */
export function parseHostWithSuffix(host: string, suffix: string): ParsedHost {
  const invalid: ParsedHost = {
    portName: '',
    taskId: null,
    isValid: false,
  };

  const dotIndex = host.indexOf('.');

  if (dotIndex === -1) {
    return invalid;
  }

  const subdomain = host.substring(0, dotIndex);
  const domain = host.substring(dotIndex); // includes the leading dot

  // Verify the subdomain ends with `-{suffix}`
  const expectedEnding = `-${suffix}`;

  if (!subdomain.endsWith(expectedEnding)) {
    return invalid;
  }

  // Strip the suffix
  const strippedSubdomain = subdomain.slice(0, -expectedEnding.length);

  if (!strippedSubdomain) {
    return invalid;
  }

  // Reconstruct host and delegate to normal parsing
  return parseHost(`${strippedSubdomain}${domain}`);
}

/**
 * Parse a nested hostname by scanning right-to-left for the outermost taskId.
 *
 * Nested URLs encode both inner and outer routing info in a single subdomain:
 *   {inner-id}-{inner-port}-{outer-id}-{outer-port}.preview.roomote.run
 *
 * The rightmost 13-char base36 taskId is the outer one.
 */
export function parseHostNested(host: string): ParsedNestedHost {
  const invalid: ParsedNestedHost = {
    outerTaskId: null,
    outerPortName: '',
    innerPrefix: '',
    isValid: false,
  };

  const dotIndex = host.indexOf('.');

  if (dotIndex === -1) {
    return invalid;
  }

  const subdomain = host.substring(0, dotIndex);
  const segments = subdomain.split('-');

  // We need at least 3 segments: inner-id, outer-id, outer-port
  if (segments.length < 3) {
    return invalid;
  }

  // Scan right-to-left for a 13-char base36 taskId segment.
  let matchIndex = -1;

  for (let i = segments.length - 1; i >= 0; i--) {
    if (TASK_ID_REGEX.test(segments[i]!)) {
      matchIndex = i;
      break;
    }
  }

  if (matchIndex < 0) return invalid;

  // Must have at least 1 segment before the match (for inner prefix)
  if (matchIndex < 1) return invalid;

  // Port name = segments after the match
  const portSegments = segments.slice(matchIndex + 1);
  const outerPortName = portSegments.join('-').toLowerCase();

  // Must have a port name
  if (!outerPortName || !PORT_NAME_REGEX.test(outerPortName)) return invalid;

  // Inner prefix = segments before the match
  const innerPrefix = segments.slice(0, matchIndex).join('-');
  if (!innerPrefix) return invalid;

  return {
    outerTaskId: segments[matchIndex]!,
    outerPortName,
    innerPrefix,
    isValid: true,
  };
}

/**
 * Strip a suffix from a hostname's subdomain.
 * If the subdomain ends with `-{suffix}`, strips it and reconstructs the host.
 * Returns the original host unchanged if the suffix is not found.
 *
 * Used by inner preview-proxies to remove the outer taskId+port suffix
 * from forwarding headers before sending to the inner sandbox's auth-proxy.
 *
 * @example
 *   stripSuffixFromHost('20imtw24sm6hv-web-r4nje6w8ab123-preview.preview.roomote.run', 'r4nje6w8ab123-preview')
 *   → '20imtw24sm6hv-web.preview.roomote.run'
 */
export function stripSuffixFromHost(host: string, suffix: string): string {
  const dotIndex = host.indexOf('.');

  if (dotIndex === -1) {
    return host;
  }

  const subdomain = host.substring(0, dotIndex);
  const domain = host.substring(dotIndex);
  const expectedEnding = `-${suffix}`;

  if (subdomain.endsWith(expectedEnding)) {
    return subdomain.slice(0, -expectedEnding.length) + domain;
  }

  return host;
}

/**
 * Parse a host using suffix stripping when a suffix is provided,
 * or normal parsing otherwise.
 */
export function parseHostForConfig(host: string, suffix?: string): ParsedHost {
  if (suffix) {
    return parseHostWithSuffix(host, suffix);
  }

  return parseHost(host);
}
