const WORKER_RELEASE_REPOSITORY_OWNER = 'Roomote';
export const WORKER_RELEASE_REPOSITORY_NAME = 'Roomote';
export const WORKER_RELEASE_REPOSITORY_FULL_NAME = `${WORKER_RELEASE_REPOSITORY_OWNER}/${WORKER_RELEASE_REPOSITORY_NAME}`;
export const WORKER_RELEASE_GITHUB_API_BASE = `https://api.github.com/repos/${WORKER_RELEASE_REPOSITORY_FULL_NAME}`;
