import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { isAbsolute, join, relative } from 'node:path';

import type { SourceControlProvider } from '@roomote/types';

/**
 * Markdown manifest written to the shared workspace root for all-repositories
 * and Blank slate workspaces. It replaces the eager clone of every active
 * repository: the agent reads this file to pick a repository, then checks it
 * out with the `clone_repository` tool.
 */
export const ON_DEMAND_REPOSITORIES_MANIFEST_FILE = 'REPOSITORIES.md';

/**
 * Runtime env flag that tells the Roomote MCP server to expose the
 * `clone_repository` tool. Set only for workspaces whose repositories are
 * checked out on demand, so scoped environment tasks never see the tool.
 */
export const ON_DEMAND_REPOSITORIES_ENV_VAR = 'ROOMOTE_ON_DEMAND_REPOSITORIES';

export const CLONE_REPOSITORY_TOOL_NAME = 'clone_repository';

export interface OnDemandRepository {
  fullName: string;
  sourceControlProvider: SourceControlProvider;
  defaultBranch: string;
  description: string | null;
  private: boolean;
}

const MAX_DESCRIPTION_LENGTH = 160;

/**
 * Resolve the checkout path for a repository full name and reject names that
 * would escape the workspace root. Full names are provider-synced, so a
 * hostile origin must never steer a path outside the workspace.
 */
export function resolveOnDemandRepositoryPath(
  workspaceRoot: string,
  fullName: string,
): string | undefined {
  const targetPath = join(workspaceRoot, fullName);
  const relativeToRoot = relative(workspaceRoot, targetPath);

  if (
    relativeToRoot === '' ||
    relativeToRoot.startsWith('..') ||
    isAbsolute(relativeToRoot)
  ) {
    return undefined;
  }

  return targetPath;
}

/**
 * Map every manifest repository that already has a git checkout under the
 * workspace root to its path. Covers snapshot resumes (clones from the
 * previous run survive) and manifest refreshes after a `clone_repository`
 * call.
 */
export function discoverClonedRepositoryPaths(
  workspaceRoot: string,
  repositories: readonly Pick<OnDemandRepository, 'fullName'>[],
): Record<string, string> {
  const repoPaths: Record<string, string> = {};

  for (const repository of repositories) {
    const repoPath = resolveOnDemandRepositoryPath(
      workspaceRoot,
      repository.fullName,
    );

    if (repoPath && existsSync(join(repoPath, '.git'))) {
      repoPaths[repository.fullName] = repoPath;
    }
  }

  return repoPaths;
}

function formatDescription(description: string | null): string {
  // Backslashes first: a raw `\|` would otherwise become `\\|`, which
  // Markdown reads as an escaped backslash followed by a live column break.
  const singleLine = (description ?? '')
    .replace(/\s+/g, ' ')
    .replace(/\\/g, '\\\\')
    .replace(/\|/g, '\\|')
    .trim();

  if (singleLine.length <= MAX_DESCRIPTION_LENGTH) {
    return singleLine;
  }

  return `${singleLine.slice(0, MAX_DESCRIPTION_LENGTH - 1).trimEnd()}…`;
}

export function buildRepositoriesManifest({
  workspaceRoot,
  repositories,
  clonedPaths,
}: {
  workspaceRoot: string;
  repositories: readonly OnDemandRepository[];
  clonedPaths: Record<string, string>;
}): string {
  const sorted = [...repositories].sort((left, right) => {
    const leftCloned = left.fullName in clonedPaths ? 0 : 1;
    const rightCloned = right.fullName in clonedPaths ? 0 : 1;

    return (
      leftCloned - rightCloned || left.fullName.localeCompare(right.fullName)
    );
  });
  const clonedCount = sorted.filter(
    (repository) => repository.fullName in clonedPaths,
  ).length;

  const lines = [
    '# Repositories',
    '',
    'This file is generated by Roomote for the current task and is rewritten when a repository is checked out.',
    `${repositories.length} ${repositories.length === 1 ? 'repository is' : 'repositories are'} available to this task; ${clonedCount} ${clonedCount === 1 ? 'is' : 'are'} checked out.`,
    '',
    `Repositories are not cloned up front. Call the \`${CLONE_REPOSITORY_TOOL_NAME}\` tool with \`repositoryFullName\` (for example \`${sorted[0]?.fullName ?? 'owner/repo'}\`) to check one out; it is cloned into \`${join(workspaceRoot, '<owner>', '<repo>')}\` and the tool returns the path. Only checked-out repositories exist on disk. Do not run \`git clone\` yourself.`,
    '',
    '| Repository | Checked out | Default branch | Visibility | Description |',
    '| --- | --- | --- | --- | --- |',
    ...sorted.map((repository) => {
      const repoPath = clonedPaths[repository.fullName];

      return `| \`${repository.fullName}\` | ${repoPath ? `yes (\`${repoPath}\`)` : 'no'} | \`${repository.defaultBranch}\` | ${repository.private ? 'private' : 'public'} | ${formatDescription(repository.description)} |`;
    }),
    '',
  ];

  return lines.join('\n');
}

export function writeRepositoriesManifest({
  workspaceRoot,
  repositories,
  clonedPaths,
}: {
  workspaceRoot: string;
  repositories: readonly OnDemandRepository[];
  clonedPaths: Record<string, string>;
}): string {
  mkdirSync(workspaceRoot, { recursive: true });

  const manifestPath = join(
    workspaceRoot,
    ON_DEMAND_REPOSITORIES_MANIFEST_FILE,
  );

  writeFileSync(
    manifestPath,
    buildRepositoriesManifest({ workspaceRoot, repositories, clonedPaths }),
    'utf8',
  );

  return manifestPath;
}
