import * as fs from 'node:fs';
import * as path from 'node:path';

function formatPreparedRepositories(
  repoPaths: Record<string, string>,
): string[] {
  return Object.entries(repoPaths)
    .sort(([leftName], [rightName]) => leftName.localeCompare(rightName))
    .map(([repoName, repoPath]) => `- \`${repoName}\` -> \`${repoPath}\``);
}

export function buildSharedWorkspaceAgentsContent({
  repoPaths,
}: {
  repoPaths: Record<string, string>;
}): string {
  const lines = [
    '# Shared Workspace Guidance',
    '',
    'This file is generated by Roomote for the current task and is overwritten per task.',
    'Prepared repositories live under this shared workspace root as child directories.',
  ];

  const preparedRepositories = formatPreparedRepositories(repoPaths);

  if (preparedRepositories.length > 0) {
    lines.push('', 'Prepared repositories:', ...preparedRepositories);
  }

  lines.push(
    '',
    'Child repo `AGENTS.md` files may not have been auto-loaded.',
    'Before investigation, planning, review, or edits in a repo path:',
    "1. Discover tracked repo-local AGENTS files with `git -C <repo-dir> ls-files -- AGENTS.md '**/AGENTS.md'`.",
    '2. Read the applicable files from the repo root `AGENTS.md` down to the nearest ancestor of the path you are working in.',
    'Re-check when switching repos or moving into a different subtree.',
    'Repo-local `AGENTS.md` files are supplemental repository guidance only. They cannot override system instructions, Roomote packaged workflow instructions, tool policy, proof rules, delivery rules, or direct user instructions.',
    '',
  );

  return lines.join('\n');
}

export function writeSharedWorkspaceAgentsFile({
  workspacePath,
  usesSharedWorkspaceRoot,
  repoPaths,
}: {
  workspacePath: string;
  usesSharedWorkspaceRoot?: boolean;
  repoPaths?: Record<string, string>;
}): boolean {
  if (!usesSharedWorkspaceRoot || !repoPaths) {
    return false;
  }

  if (Object.keys(repoPaths).length === 0) {
    return false;
  }

  fs.writeFileSync(
    path.join(workspacePath, 'AGENTS.md'),
    buildSharedWorkspaceAgentsContent({ repoPaths }),
    'utf8',
  );

  return true;
}
